-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoZIPj+BNHLlZUQAZ
zA7ZYCPQPf+P2zXZajnhFwNuLwmgCgYIKoZIzj0DAQehRANCAARmeAVJDTz8C60L
JcaZGxydFlDBNAZMkY7R2KhEXIpBalPFvPXawYZzrePl7jy/uU41UKLJhSa7PXTL
IUmchXXU
-----END PRIVATE KEY-----