-- ============================================================
-- SEED 9: 30 curated tours (Sternfahrten von Röbel)
-- Hand-built editorial moat. Komoot will never have this.
-- Categories: familie, sonnenuntergang, sonnenaufgang, faehre_kombi,
--             bus_kombi, badewetter, schlechtwetter, wildlife, altstadt,
--             kultur, naturpark, flach, hafen, rundtour, einweg, kinder,
--             wandern, rad.
-- ============================================================

INSERT INTO tours (
  slug, title_de, subtitle_de, description_de,
  start_lat, start_lon, start_label_de,
  distance_km, duration_min, elevation_gain_m, surface_de,
  difficulty, categories, hours_bucket,
  is_sternfahrt, ferry_combo, bus_combo,
  has_swim_stop, has_eis_stop, family_friendly, bad_weather_alternative,
  season_de, best_start_time_de, return_options_de,
  highlights_de, warnings_de
) VALUES
-- ─── Familie / Leicht (5) ──────────────────────────────────────
('marienfelde-schleife',
 'Marienfelde-Schleife',
 'Mit dem Stadtbus 024 raus, mit Mecky zurück',
 'Sanfter Familien-Klassiker: mit der Linie 024 nach Marienfelde Schloß, dann gemütlich am Ufer entlang zurück zum Stadthafen. Kein Höhenmeter, viele Pausen.',
 53.3680, 12.6037, 'Müritztherme · Bahnhofstraße',
 6.5, 90, 0, 'Asphalt + Plattenweg',
 'leicht', ARRAY['familie','flach','rad','rundtour','bus_kombi'], '2h',
 true, false, true, false, true, true, false,
 'ganzjährig', 'mittags',
 'Linie 024 fährt 09:08, 10:08, 12:08, 14:08, 16:08 ab Bahnhofstraße/Therme zurück.',
 '["Marienfelde Schloß","Strandbad Marienfelde mit Sandstrand","Eisdiele am Hafen"]'::jsonb,
 '["Sonntags fährt der Stadtbus nicht — dann hin und zurück mit dem Rad"]'::jsonb),

('hafen-promenade-3km',
 'Hafen-Promenade 3 km',
 'Kürzeste Mecky-Tour — perfekt mit Kinderwagen',
 'Drei flache Kilometer entlang der Müritzpromenade von der Tourist-Info bis zur Engelschen Mühle und zurück. Schnell mal eingeschoben zwischen Frühstück und Mittag.',
 53.3672, 12.5985, 'Tourist-Info · Haus des Gastes',
 3.0, 45, 0, 'Asphalt',
 'leicht', ARRAY['familie','flach','wandern','altstadt','hafen','rundtour'], '2h',
 true, false, false, false, true, true, false,
 'ganzjährig', 'flexibel',
 'Rundtour — keine Verbindung nötig.',
 '["Stadthafen Röbel","Engelsche Mühle (Café-Stopp)","Marktplatz Altstadt"]'::jsonb,
 '[]'::jsonb),

('ludorf-grosser-schwerin',
 'Ludorf · Großer Schwerin',
 'NSG-Blicke ohne den Park zu betreten',
 'Mecky empfiehlt: das Naturschutzgebiet Großer Schwerin von außen — ruhig, Vogelreich, mit Schwimmstopp am Westufer.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 18.0, 150, 5, 'Asphalt + Schotter',
 'leicht', ARRAY['familie','wildlife','badewetter','flach','rad','rundtour'], '4h',
 true, false, false, true, false, true, false,
 'Mai – September', 'morgens',
 'Über Ludorfer Straße zurück.',
 '["Ludorf Schloß","NSG Großer Schwerin (Vogelblicke)","Sandstrand Klink (optional Wende)"]'::jsonb,
 '["NSG: nur an markierten Stellen baden, Vögel nicht stören"]'::jsonb),

('klink-strand-tour',
 'Klink-Strand-Tour',
 'Auf der Müritz-Ringstraße zum großen Sandstrand',
 'Klink hat den größten Sandstrand am Westufer — über die fast völlig ebene Müritz-Ringstraße in einer halben Stunde da. Eis am Anleger, Müritzschiff zurück möglich.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 28.0, 180, 10, 'Asphalt',
 'leicht', ARRAY['familie','badewetter','flach','rad','faehre_kombi','hafen'], 'tag',
 true, true, false, true, true, true, false,
 'Mai – September', '10:00 für MS Diana 16:00 zurück',
 'MS Diana von Klink zurück nach Röbel · Saison 18.04. – Anf. Okt.',
 '["Sandstrand Klink","Schloss Klink","Eisdiele am Anleger"]'::jsonb,
 '["MS Diana fährt nicht sonntags — dann beide Richtungen mit dem Rad"]'::jsonb),

('engelsche-muehle-altstadt',
 'Engelsche Mühle · Altstadt-Spaziergang',
 'Fachwerk, Mühle, Marktplatz',
 'Eineinhalb Stunden zu Fuß durch die Röbeler Altstadt — Marktplatz, Mühle, Marienkirche. Mecky-Klassiker für regnerische Tage.',
 53.3666, 12.5994, 'Marktplatz Röbel',
 2.5, 90, 0, 'Pflaster + Asphalt',
 'leicht', ARRAY['familie','altstadt','kultur','flach','wandern','rundtour','schlechtwetter'], '2h',
 true, false, false, false, true, true, true,
 'ganzjährig', 'flexibel',
 'Rundtour.',
 '["Marienkirche mit 58 m Aussichtsplattform","Engelsche Mühle mit Mühlenmuseum","Café am Markt"]'::jsonb,
 '[]'::jsonb),

-- ─── Wildlife / Aktiv (6) ─────────────────────────────────────
('beobachtungsstand-tour-32km',
 '32 km Beobachtungsstand-Tour',
 'Acht Stände an einem Tag',
 'Die kanonische Vogelbeobachtungs-Tour: von Waren über Schnakenburg, Warnker See, Rederangsee, Specker See, Müritzblick, Boek bis zum Wildpark. Mecky-Empfehlung für Vogelfans.',
 53.5180, 12.6900, 'Waren Bahnhof',
 32.0, 360, 30, 'Wassergebundene Decke + Asphalt',
 'mittel', ARRAY['wildlife','naturpark','rad','einweg','rundtour'], 'tag',
 false, false, true, false, false, false, false,
 'Apr – Okt (Kraniche: Sep – Nov)',
 '08:00 Start für volle Beobachtungschancen',
 'Linie 12 oder Nationalpark-Linie 9 ab Boek zurück nach Waren / Röbel.',
 '["8 Beobachtungsstände","Live-Webcam Fischadler in Federow","Wildpark Boek am Schluss"]'::jsonb,
 '["Aug–Okt: Rederangsee 16h–dunkel nur mit Ranger­führung"]'::jsonb),

('specker-seen-rundkurs',
 '21 km Specker Seen Rundkurs',
 'Wasservögel, Silberreiher, 800-jährige Sommerlinde',
 'Kompakter Wildlife-Loop um Specker Hofsee und Specker See — flache 21 km mit dem 800 Jahre alten Lindenbaum als Mittelpunkt.',
 53.5050, 12.7200, 'Speck',
 21.0, 180, 15, 'Wassergebundene Decke',
 'mittel', ARRAY['wildlife','naturpark','rad','rundtour'], '4h',
 false, false, true, false, false, true, false,
 'Apr – Okt', 'früh morgens',
 'Nationalpark-Linie 10 ab Speck.',
 '["Aussichtspunkt Hofsee mit 800-jähriger Sommerlinde","Beobachtungsstand Specker Hofsee","Beobachtungsstand Specker See"]'::jsonb,
 '[]'::jsonb),

('vogel-und-wild-48km',
 '48 km Vogel- und Wildbeobachtung',
 'Die ausführliche Mecky-Variante',
 'Längere Schwester der 32 km Tour — fügt die Warnker Seen Süd, Zartwitzer Fischteiche und Amalienhof hinzu. Für ehrgeizige Beobachter mit ganzem Tag.',
 53.5180, 12.6900, 'Waren Bahnhof',
 48.0, 480, 50, 'Wassergebundene Decke + Asphalt',
 'sportlich', ARRAY['wildlife','naturpark','rad','einweg'], 'tag',
 false, false, true, false, false, false, false,
 'Apr – Okt', '07:30',
 'Linie 12 ab Boek/Röbel.',
 '["Schnakenburg","Warnker See Nord & Süd","Zartwitzer Fischteiche","Federow Fischadler-Webcam","Amalienhof","Wildpark Boek"]'::jsonb,
 '["Aug–Okt: Rederangsee Zugangsregeln beachten"]'::jsonb),

('mueritz-rundweg-86km',
 '86 km Müritz-Rundweg',
 'Einmal um Deutschlands größten Binnensee',
 'Praktisch flach (gesamt 33 m Höhenunterschied). Ostseite durch Wald & Moor mit Adler-Chancen, Westseite mit Müritzblick und Klinker Sandstrand. 1 Tag sportlich, 2 Tage gemütlich.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 86.0, 480, 33, 'Asphalt + Wassergebundene Decke',
 'sportlich', ARRAY['naturpark','rad','rundtour','flach','wildlife'], 'tag',
 true, false, false, true, false, false, false,
 'Mai – Sept', '07:00',
 'Rundtour ab Röbel.',
 '["Klink Sandstrand","Waren Stadthafen","Müritz-Nationalpark Ostufer","Großer Schwerin (NSG)"]'::jsonb,
 '["Sonntags wenig Versorgung im Park — Snacks mitnehmen"]'::jsonb),

('mueritz-wanderweg-mehrtag',
 '175 km Müritz-Nationalpark-Wanderweg',
 'Mehrtagestour zu Fuß',
 'Der große Wanderweg von Waren bis Serrahn (UNESCO-Buchenwald) und zurück. Auf 4–5 Etappen aufteilen, mit Einkehr in Federow, Speck, Boek und Schwarzenhof.',
 53.5180, 12.6900, 'Waren Bahnhof',
 175.0, 2700, 200, 'Wassergebundene Decke + Naturweg',
 'sportlich', ARRAY['naturpark','wandern','wildlife','einweg'], 'mehrtag',
 false, false, true, false, false, false, false,
 'Mai – Okt', 'Etappenstart 08:00',
 'Übernachtungen in Pensionen Federow/Speck/Boek; Rückreise mit Linie 12.',
 '["UNESCO-Welterbe Serrahn","8+ Beobachtungsstände","Käflingsbergturm 55 m"]'::jsonb,
 '["Zecken hoch — Repellent und Körpercheck Pflicht"]'::jsonb),

('federow-fischadler-tour',
 'Fischadlernest Federow',
 'Live-Cam, Brutstand, Information­shaus',
 'Mecky-Klassiker im Frühjahr: Federow Information mit Live-Webcam vom Fischadlernest. Mitte Mai zeigen sich die ersten Küken. Drumherum: zwei Beobachtungsstände in Sichtweite.',
 53.4783, 12.7367, 'Federow Information',
 12.0, 150, 10, 'Wassergebundene Decke',
 'leicht', ARRAY['wildlife','naturpark','familie','rad'], '2h',
 false, false, true, false, false, true, false,
 'März – September', '09:00',
 'Nationalpark-Linie 9 zurück.',
 '["Live-Webcam Fischadlernest","Information­shaus Federow","Beobachtungsstand Federow"]'::jsonb,
 '["Erste Küken Mitte Mai — vorher Brutgeschehen, weniger Sichtungen"]'::jsonb),

-- ─── Bike + Schiff (4) ────────────────────────────────────────
('bike-msdiana-klink-roebel',
 'Bike + MS Diana · Klink ↔ Röbel',
 'Hin radeln, zurück schippern',
 'Asymmetrische Sternfahrt: 28 km am Westufer nach Klink, dann mit MS Diana entspannt zurück nach Röbel. Mecky-Empfehlung für sonnige Tage.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 28.0, 180, 10, 'Asphalt',
 'leicht', ARRAY['rad','faehre_kombi','badewetter','flach','familie','einweg'], 'tag',
 true, true, false, true, true, true, false,
 '18.04. – Anf. Okt (Mo–Sa)', '10:00 hin · 16:00 Schiff zurück',
 'MS Diana ab Klink Anleger zurück nach Röbel · 4-Seenfahrt nach Malchow als Alternative.',
 '["Sandstrand Klink","Schloss Klink","MS Diana barrierefrei"]'::jsonb,
 '["Sonntags kein Schiff"]'::jsonb),

('msdiana-bolter-bike-roebel',
 'MS Diana → Bolter Kanal → Bike zurück',
 'Mecky-Asymmetrie: erst Schiff, dann Rad',
 'Mit MS Diana zur Schleuse Bolter Kanal, dann Bike durch den Park über Boek und Federow zurück. 35 km Land + 1 h Wasser.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 35.0, 360, 25, 'Wassergebundene Decke + Asphalt',
 'mittel', ARRAY['rad','faehre_kombi','wildlife','naturpark','einweg'], 'tag',
 true, true, true, false, false, false, false,
 '18.04. – Anf. Okt (Mo–Sa)', 'MS Diana 09:30 ab Röbel',
 'Mit dem Rad über Boek → Federow → Linie 12 ab Federow oder direkt zurück.',
 '["Schleuse Bolter Kanal","Wildpark Boek","Live-Webcam Federow"]'::jsonb,
 '["Sonntags kein Schiff"]'::jsonb),

('mirow-tagesfahrt',
 'Tagesfahrt zur Schlossinsel Mirow',
 'Sieben Stunden Schiff, eine Stunde Schloss',
 'Die längste MS-Diana-Tour ab Röbel: 11:00 Abfahrt, 18:00 zurück. Drei Stunden auf dem Schloss in Mirow erkunden — Mecky-Tipp für regnerische Tage.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 0.0, 420, 0, 'auf dem Wasser',
 'leicht', ARRAY['faehre_kombi','kultur','familie','schlechtwetter','einweg'], 'tag',
 true, true, false, false, false, true, true,
 '18.04. – Anf. Okt (Mo–Sa)', '11:00 Abfahrt',
 'MS Diana Hin- und Rückfahrt.',
 '["Schloss Mirow","Schlossinsel Spaziergang","Bordrestaurant"]'::jsonb,
 '["Schiff fährt sonntags nicht"]'::jsonb),

('klink-baden-schiff-zurueck',
 'Klink Sandstrand · Schiff zurück',
 'Halber Tag Strand + 1 h Wasser',
 'Mecky-Familienklassiker: hin radeln, am Sandstrand spielen, mit MS Diana zurück. Ideal für 35 °C-Tage.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 28.0, 240, 10, 'Asphalt',
 'leicht', ARRAY['familie','badewetter','faehre_kombi','rad','flach','einweg'], 'tag',
 true, true, false, true, true, true, false,
 'Juni – August', '10:00',
 'MS Diana 16:00 ab Klink.',
 '["Sandstrand Klink (bewacht)","MS Diana 16:00 ab Klink"]'::jsonb,
 '["Sonntags kein Schiff"]'::jsonb),

-- ─── Themed / Cultural (5) ────────────────────────────────────
('schliemann-ankershagen',
 'Heinrich-Schliemann-Tour',
 'Trojanisches Pferd in Ankershagen',
 'Themen-Sternfahrt für Geschichts­fans: Ankershagen mit dem Schliemann-Museum und einem trojanischen Pferd zum Hineinklettern. Auch die Havelquelle dort.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 36.0, 360, 30, 'Asphalt',
 'mittel', ARRAY['kultur','rad','familie','rundtour'], 'tag',
 true, false, false, false, false, true, true,
 'Apr – Okt', '09:30',
 'Rundtour über Federow.',
 '["Schliemann-Museum","Trojanisches Pferd zum Anfassen","Havelquelle"]'::jsonb,
 '[]'::jsonb),

('speck-kaeflingsberg-linde',
 'Speck · Käflingsbergturm · 800-jährige Linde',
 'Drei Höhepunkte auf einer Tour',
 'Mecky-Tour mit dem 55-Meter-Käflingsbergturm (167 Stufen, 31 m Plattform, 360°-Blick), dem Aussichtspunkt Hofsee und der 800 Jahre alten Sommerlinde.',
 53.5180, 12.6900, 'Waren Bahnhof',
 24.0, 240, 80, 'Wassergebundene Decke',
 'mittel', ARRAY['naturpark','rad','kultur','wandern','rundtour'], '4h',
 false, false, true, false, false, false, false,
 'Apr – Okt', '10:00',
 'Nationalpark-Linie 10 ab Speck.',
 '["Käflingsbergturm 360° Aussicht","800-jährige Sommerlinde","Hofsee Aussichtspunkt"]'::jsonb,
 '["167 Stufen — kleine Kinder können oben festgehalten werden"]'::jsonb),

('boek-zinnfiguren-wildpark',
 'Boek · Zinnfigurenmuseum · Wildpark',
 'Familienpaket im Park',
 'Boek auf einen halben Tag: Wildpark mit Rotwild und Damwild, Zinnfigurenmuseum als Schlechtwetter-Backup, Eisdiele am Hauptplatz.',
 53.4408, 12.7900, 'Boek',
 6.0, 180, 0, 'Asphalt',
 'leicht', ARRAY['familie','kultur','naturpark','schlechtwetter','rundtour'], '2h',
 false, false, true, false, true, true, true,
 'Apr – Okt', 'mittags',
 'Nationalpark-Linie 9 ab Boek.',
 '["Wildpark Boek","Zinnfigurenmuseum","Eisdiele Boek"]'::jsonb,
 '[]'::jsonb),

('mueritzeum-tag',
 'Müritzeum-Tag in Waren',
 'Deutschlands größtes Süßwasseraquarium',
 'Mecky-Empfehlung bei Regen: das Müritzeum mit dem größten Süßwasseraquarium Deutschlands. Mit dem Schiff oder Bus hin, gemütlich zurück.',
 53.5180, 12.6900, 'Waren Bahnhof',
 1.0, 240, 0, 'Pflaster',
 'leicht', ARRAY['kultur','familie','schlechtwetter','wandern'], 'tag',
 false, true, true, false, true, true, true,
 'ganzjährig', '10:00 Eintritt',
 'Linie 12 oder MS Diana zurück nach Röbel.',
 '["Süßwasseraquarium","Naturkundliche Ausstellung","Café"]'::jsonb,
 '[]'::jsonb),

('1858-walk-roebel',
 '1858 · Röbel-Wappenwalk',
 'Mecky erzählt die Stadtgeschichte',
 'Spaziergang durch die Röbeler Altstadt von 1858: Marktplatz, Marienkirche, Engelsche Mühle, alte Hafenmauern. Mit Mecky-Wegweisern.',
 53.3666, 12.5994, 'Marktplatz Röbel',
 2.0, 75, 0, 'Pflaster + Asphalt',
 'leicht', ARRAY['altstadt','kultur','familie','wandern','rundtour','flach'], '2h',
 true, false, false, false, true, true, true,
 'ganzjährig', 'nachmittags',
 'Rundtour.',
 '["Marienkirche 58 m Turm","Engelsche Mühle","Stadtmauer-Reste"]'::jsonb,
 '[]'::jsonb),

-- ─── Bad-Weather Alternates (3) ──────────────────────────────
('mueritzeum-indoor',
 'Indoor: Müritzeum',
 'Schlechtwetter-Plan A',
 'Drei Stunden im Müritzeum, mit dem Schiff oder Bus hin und zurück. Mecky-Tipp wenn der Regen mal nicht aufhört.',
 53.5176, 12.6790, 'Müritzeum Waren',
 0.5, 180, 0, 'Pflaster',
 'leicht', ARRAY['schlechtwetter','familie','kultur','wandern'], '4h',
 false, true, true, false, true, true, true,
 'ganzjährig', 'flexibel',
 'Linie 12 / MS Diana.',
 '["Größtes Süßwasseraquarium Deutschlands"]'::jsonb,
 '[]'::jsonb),

('therme-schliemann',
 'Indoor-Doppelpack: Therme + Schliemann',
 'Wellness vormittags, Geschichte nachmittags',
 'Mecky-Doppel für Regentage: morgens in die Müritztherme, mittags weiter zum Schliemann-Museum nach Ankershagen.',
 53.3680, 12.6037, 'Müritztherme Röbel',
 33.0, 480, 30, 'Asphalt + Innen',
 'mittel', ARRAY['schlechtwetter','familie','kultur','rad'], 'tag',
 true, false, false, false, false, true, true,
 'ganzjährig', '09:00',
 'Rad zurück, alternativ Linie 12.',
 '["Müritztherme (Gästekarten-Rabatt)","Schliemann-Museum"]'::jsonb,
 '[]'::jsonb),

('engelsche-marienkirche',
 'Indoor: Engelsche Mühle + Marienkirche',
 'Zwei Häuser, eine Stunde',
 'Klassischer Schlechtwetter-Walk: Mühlenmuseum, dann Marienkirche-Turm. Mit dem Schirm 800 Meter zwischen beiden.',
 53.3669, 12.5970, 'Engelsche Mühle',
 1.0, 60, 0, 'Pflaster',
 'leicht', ARRAY['schlechtwetter','altstadt','kultur','familie','wandern','rundtour'], '2h',
 true, false, false, false, true, true, true,
 'Mai – Okt (Öffnungszeiten)', 'flexibel',
 'Rundtour.',
 '["Mühlenmuseum","Marienkirche 58 m Turm"]'::jsonb,
 '[]'::jsonb),

-- ─── Seasonal Mecky-Specials (4) ─────────────────────────────
('kraniche-sonnenaufgang',
 'Kraniche · Sonnenaufgang Rederangsee',
 'Der Showpiece-Moment der Müritz',
 '4:30 aufstehen, mit dem Rad oder Bus zur Kranich-Schlafplatz Rederangsee. Bei Sonnenaufgang fliegen bis zu 8.000 Kraniche zeitgleich auf — Gänsehaut.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 24.0, 180, 25, 'Wassergebundene Decke',
 'mittel', ARRAY['wildlife','naturpark','sonnenaufgang','rad'], '4h',
 false, false, true, false, false, false, false,
 '15.08. – 31.10.', 'Sonnenaufgang -30 min',
 'Linie 12 zurück.',
 '["Bis zu 8.000 Kraniche zeitgleich","Sonnenaufgang über dem Rederangsee","Mecky-Wachsamkeit für absolute Stille"]'::jsonb,
 '["Aug–Okt: 16h–dunkel nur mit Ranger­führung — frühmorgens kostenfrei zugänglich"]'::jsonb),

('fischadler-brut-mai',
 'Fischadler-Brut-Tour Federow',
 'Live-Webcam zeigt die ersten Küken',
 'Mecky-Mai-Klassiker: Fischadler in Federow brüten. Live-Cam im Information­shaus. Mitte Mai sind die ersten Küken da.',
 53.4783, 12.7367, 'Federow Information',
 12.0, 150, 10, 'Wassergebundene Decke',
 'leicht', ARRAY['wildlife','naturpark','familie','rad'], '2h',
 false, false, true, false, false, true, false,
 'Mitte Mai – Mitte Juni', '09:00',
 'Nationalpark-Linie 9.',
 '["Live-Webcam Brutgeschehen","Erste Küken Mitte Mai"]'::jsonb,
 '[]'::jsonb),

('hirschbrunft-schwarzenhof',
 'Hirschbrunft Schwarzenhof',
 'Spätsommer-Abend mit Röhren',
 'Mitte September bis Mitte Oktober brunften die Rothirsche. Schwarzenhof bietet Ranger­führungen am Abend — kombiniert mit der Kraniche-Schlafplatz-Suche.',
 53.4800, 12.7150, 'Schwarzenhof',
 8.0, 180, 15, 'Wassergebundene Decke',
 'mittel', ARRAY['wildlife','naturpark','sonnenuntergang','wandern'], '4h',
 false, false, true, false, false, false, false,
 '15.09. – 15.10.', 'eine Stunde vor Sonnenuntergang',
 'Nationalpark-Linie 10 / 9.',
 '["Hirschbrunft mit Ranger","Kombi mit Kranich-Schlafplatz"]'::jsonb,
 '["Geführte Touren — bei Verein anmelden"]'::jsonb),

('kranichtanz-fruehjahr',
 'Kranichtanz im Frühjahr',
 'Werbungstanz auf den Wiesen',
 'Das wenig bekannte Spektakel: Mitte März bis Anfang April tanzen die Kraniche auf den Wiesen ihre Werbung. Mecky-Geheimtipp.',
 53.5180, 12.6900, 'Waren Hauswiesen',
 8.0, 120, 10, 'Wassergebundene Decke',
 'leicht', ARRAY['wildlife','naturpark','familie','wandern'], '2h',
 false, false, true, false, false, true, false,
 '15.03. – 10.04.', 'morgens',
 'Linie 12.',
 '["Werbungstanz der Kraniche","Warener Hauswiesen Beobachtungsstand"]'::jsonb,
 '[]'::jsonb),

-- ─── Sunset / Special (3) ─────────────────────────────────────
('sonnenuntergang-hafen',
 'Sonnenuntergang am Stadthafen',
 'Mecky-Goldene-Stunde-Loop',
 'Eine Stunde vor Sonnenuntergang am Stadthafen starten, Promenade entlang nach Marienfelde, Sonnenuntergang über der Müritz, gemütlich zurück.',
 53.3692, 12.5898, 'Stadthafen Röbel',
 4.0, 90, 0, 'Asphalt + Plattenweg',
 'leicht', ARRAY['sonnenuntergang','familie','flach','wandern','rundtour','hafen'], '2h',
 true, false, false, false, true, true, false,
 'Mai – September', 'eine Stunde vor Sonnenuntergang',
 'Rundtour.',
 '["Sonnenuntergang über der Müritz","Eisdiele am Hafen"]'::jsonb,
 '[]'::jsonb),

('sundowner-eisdiele',
 'Sundowner mit Eisdiele',
 'Faulste Mecky-Tour der Liste',
 'Vom Hotel zur Promenade, Eis essen, Sonnenuntergang anschauen, zurück. Insgesamt 1,5 km, eine Stunde, perfekter Anreisetag-Spaziergang.',
 53.3666, 12.5994, 'Marktplatz Röbel',
 1.5, 60, 0, 'Pflaster + Asphalt',
 'leicht', ARRAY['familie','sonnenuntergang','altstadt','flach','wandern','rundtour','hafen'], '2h',
 true, false, false, false, true, true, false,
 'ganzjährig', 'eine Stunde vor Sonnenuntergang',
 'Rundtour.',
 '["Eisdiele","Sonnenuntergang Hafen"]'::jsonb,
 '[]'::jsonb),

('singschwaene-schnakenburg',
 'Singschwäne · Schnakenburg',
 'Winterhighlight Dezember bis März',
 'Im Winter rasten Singschwäne bei Schnakenburg. Vom Bahnhof Waren ein Spaziergang zum Beobachtungsstand — kalte Füße, glücklich.',
 53.5180, 12.6900, 'Waren Bahnhof',
 7.0, 150, 5, 'Wassergebundene Decke',
 'leicht', ARRAY['wildlife','naturpark','familie','wandern','rundtour'], '4h',
 false, false, true, false, false, true, false,
 'Dez – März', 'mittags',
 'Linie 12.',
 '["Singschwäne","Beobachtungsturm Schnakenburg"]'::jsonb,
 '["Wirklich kalt im Februar — warme Schichten"]'::jsonb);

-- ─── Mark today''s Mecky-Tipp ────────────────────────────────
UPDATE tours SET is_meckys_tipp_today = true WHERE slug = 'sundowner-eisdiele';

-- ─── Sample tour stops for the flagship tours ─────────────────
-- Beobachtungsstand-Tour 32 km — full stop sequence from user research
INSERT INTO tour_stops (tour_id, stop_order, name_de, lat, lon, km_from_start, stop_type)
SELECT t.id, s.ord, s.name, s.lat, s.lon, s.km, s.tp::text FROM tours t
CROSS JOIN (VALUES
  (1, 'Waren Bahnhof', 53.5180, 12.6900, 0.0, 'start'),
  (2, 'Vogelbeobachtungsturm Schnakenburg', 53.4831, 12.7194, 3.5, 'observation_stand'),
  (3, 'Beobachtungspunkt Warnker See', 53.4680, 12.6850, 5.5, 'observation_stand'),
  (4, 'Vogelbeobachtungsturm Rederangsee', 53.5067, 12.6900, 10.0, 'observation_stand'),
  (5, 'Beobachtungsstand Specker See', 53.5008, 12.7095, 15.5, 'observation_stand'),
  (6, 'Specker Horst', 53.4990, 12.7150, 16.5, 'observation_stand'),
  (7, 'Beobachtungsstand Binnenmüritz', 53.4900, 12.6700, 17.0, 'observation_stand'),
  (8, 'Beobachtungsstand Müritzblick', 53.4750, 12.6900, 19.5, 'observation_stand'),
  (9, 'Boek', 53.4408, 12.7900, 22.0, 'transit_stop'),
  (10, 'Wildpark Boek', 53.4408, 12.7900, 23.0, 'finish')
) AS s(ord, name, lat, lon, km, tp)
WHERE t.slug = 'beobachtungsstand-tour-32km';

-- Hafen-Promenade
INSERT INTO tour_stops (tour_id, stop_order, name_de, lat, lon, km_from_start, stop_type)
SELECT t.id, s.ord, s.name, s.lat, s.lon, s.km, s.tp::text FROM tours t
CROSS JOIN (VALUES
  (1, 'Tourist-Info · Haus des Gastes', 53.3672, 12.5985, 0.0, 'start'),
  (2, 'Stadthafen Röbel', 53.3692, 12.5898, 0.5, 'viewpoint'),
  (3, 'Engelsche Mühle', 53.3669, 12.5970, 1.5, 'sehenswuerdigkeit'),
  (4, 'Marktplatz', 53.3666, 12.5994, 3.0, 'finish')
) AS s(ord, name, lat, lon, km, tp)
WHERE t.slug = 'hafen-promenade-3km';

-- Klink-Strand-Tour
INSERT INTO tour_stops (tour_id, stop_order, name_de, lat, lon, km_from_start, stop_type)
SELECT t.id, s.ord, s.name, s.lat, s.lon, s.km, s.tp::text FROM tours t
CROSS JOIN (VALUES
  (1, 'Stadthafen Röbel', 53.3692, 12.5898, 0.0, 'start'),
  (2, 'Ludorf Schloß', 53.3989, 12.6228, 7.0, 'sehenswuerdigkeit'),
  (3, 'Sandstrand Klink', 53.5006, 12.6411, 18.0, 'swim_spot'),
  (4, 'Klink Anleger MS Diana', 53.5006, 12.6411, 18.5, 'finish')
) AS s(ord, name, lat, lon, km, tp)
WHERE t.slug = 'klink-strand-tour';

-- Federow Fischadler-Tour
INSERT INTO tour_stops (tour_id, stop_order, name_de, lat, lon, km_from_start, stop_type)
SELECT t.id, s.ord, s.name, s.lat, s.lon, s.km, s.tp::text FROM tours t
CROSS JOIN (VALUES
  (1, 'Federow Information', 53.4783, 12.7367, 0.0, 'start'),
  (2, 'Beobachtungsstand Federow', 53.4783, 12.7367, 1.5, 'observation_stand'),
  (3, 'Live-Webcam Brutbaum', 53.4790, 12.7400, 2.0, 'observation_stand'),
  (4, 'Federow Information', 53.4783, 12.7367, 12.0, 'finish')
) AS s(ord, name, lat, lon, km, tp)
WHERE t.slug = 'federow-fischadler-tour';
