import type { NetizenManifest } from "@netizen-labs/protocol";

/**
 * The PURE core of `netizen render`: manifest → an inspectable bundle
 * (config files + an ordered plan). No I/O, no infra, deterministic — this is
 * what we TDD. Secrets are emitted only as references, never resolved.
 * See docs/superpowers/specs/2026-07-26-netizen-node-installer.md.
 */

export interface Step {
  id: string;
  phase: string;
  title: string;
}

export interface Bundle {
  /** relative path → file contents */
  files: Record<string, string>;
  plan: Step[];
  /** every $REF / vault: the operator must supply before `up` */
  secretRefs: string[];
}

/**
 * Does this node's stack need a database?
 *
 * Derived from `postgresDatabases()` rather than re-listing the services that
 * use one. The two drifted apart once: `postgresDatabases()` gave the indexer a
 * database while this function only knew about the workspace and Matrix, so a
 * relay + index node rendered an indexer whose DATABASE_URL pointed at a
 * postgres host that was never created. Röbel declared Nextcloud, which hid it
 * until the node was trimmed to relay + index. One list, one answer.
 */
export function composeNeedsPostgres(m: NetizenManifest): boolean {
  return postgresDatabases(m).length > 0;
}

const rp = (m: NetizenManifest, id: string) =>
  m.identity?.relyingParties.find((r) => r.id === id);

const header = (m: NetizenManifest, what: string) =>
  `# Generated by \`netizen render\` — ${what} for node "${m.id}"\n`;

/** Best-effort hostname from an http(s) or wss url. */
function hostname(u: string): string {
  try {
    return new URL(u).hostname;
  } catch {
    return u.replace(/^[a-z]+:\/\//, "").replace(/\/.*$/, "");
  }
}

export function renderRoebelIdEnv(m: NetizenManifest): string {
  const nc = rp(m, "nextcloud");
  const mx = rp(m, "matrix");
  const web = rp(m, "web");
  const s = m.services.secrets ?? {};
  // Reached only for a node that hosts its own IdP — which by definition
  // authenticates against a chain and a membership credential. Fail loudly rather
  // than emitting an env file with empty values that would fail at runtime.
  const { identity, chain, contracts } = m;
  if (!identity || !chain || !contracts) {
    throw new Error(
      "cannot render the keystone env: a self-hosted IdP needs identity, chain and contracts declared",
    );
  }
  const lines = [
    header(m, "Röbel ID keystone env").trimEnd(),
    `ISSUER_URL=${identity.idp.issuer}`,
    `CHAIN_ID=${chain.chainId}`,
    `GNOSIS_RPC_URL=${chain.rpc}`,
    `CITIZEN_NFT_ADDRESS=${contracts.citizenNft}`,
    `ATTESTER_NFT_ADDRESS=${contracts.attesterNft}`,
    `THIRDWEB_CLIENT_ID=$THIRDWEB_CLIENT_ID`,
    `JWKS_JSON=${identity.idp.jwks}`,
  ];
  if (nc) {
    lines.push(
      `NEXTCLOUD_CLIENT_ID=${nc.id}`,
      `NEXTCLOUD_CLIENT_SECRET=${s.nextcloudClientSecret ?? "$NEXTCLOUD_CLIENT_SECRET"}`,
      `NEXTCLOUD_REDIRECT_URIS=${nc.redirectUris.join(",")}`,
    );
  }
  if (mx) {
    lines.push(
      `MATRIX_CLIENT_ID=${mx.id}`,
      `MATRIX_CLIENT_SECRET=${s.matrixClientSecret ?? "$MATRIX_CLIENT_SECRET"}`,
      `MATRIX_REDIRECT_URIS=${mx.redirectUris.join(",")}`,
    );
  }
  if (web) {
    lines.push(
      `WEB_CLIENT_ID=${web.id}`,
      `WEB_CLIENT_SECRET=${s.webClientSecret ?? "$WEB_CLIENT_SECRET"}`,
      `WEB_REDIRECT_URIS=${web.redirectUris.join(",")}`,
    );
  }
  return lines.join("\n") + "\n";
}

/**
 * App env — one line per workspace surface the node declares. Each var lights up
 * exactly one dashboard tile (citizen + org), so a node ships with the subset it runs.
 */
export function renderWebEnv(m: NetizenManifest): string {
  const ws = m.services.workspace;
  const pairs: Array<[string, string | undefined]> = [
    ["NEXT_PUBLIC_WORKSPACE_BASE_URL", ws?.nextcloud],
    ["NEXT_PUBLIC_CHAT_BASE_URL", m.services.chat?.matrix?.element],
    ["NEXT_PUBLIC_MAIL_BASE_URL", ws?.mail],
    ["NEXT_PUBLIC_WIKI_BASE_URL", ws?.wiki],
    ["NEXT_PUBLIC_VIDEO_BASE_URL", ws?.video],
    ["NEXT_PUBLIC_PROJECT_BASE_URL", ws?.project],
    ["NEXT_PUBLIC_AGENTS_BASE_URL", ws?.portal],
    ["NEXT_PUBLIC_BUZZ_BASE_URL", m.services.buzz?.url],
  ];
  const lines = [header(m, "web app env").trimEnd()];
  for (const [key, value] of pairs) if (value) lines.push(`${key}=${value}`);
  return lines.join("\n") + "\n";
}

export function renderElementConfig(m: NetizenManifest): string {
  const hs = m.services.chat?.matrix?.homeserver ?? "";
  return (
    JSON.stringify(
      { default_server_config: { "m.homeserver": { base_url: hs } }, default_country_code: "DE" },
      null,
      2,
    ) + "\n"
  );
}

/**
 * Matrix Authentication Service — the FULL config, not a fragment.
 *
 * MAS owns all authentication; Synapse delegates to it via MSC3861. Local
 * passwords and registration are disabled on purpose: the node's own keystone is
 * the only way in, so identity stays sovereign and there is no password shadow
 * account to compromise.
 *
 * Secrets are ${PLACEHOLDERS} substituted on the box at apply time, and signing
 * keys are referenced by path (never inlined) so no key material is ever written
 * into a rendered bundle.
 */
export function renderMasConfig(m: NetizenManifest): string {
  const mx = rp(m, "matrix");
  const matrix = m.services.chat?.matrix;
  const callback = mx?.redirectUris[0] ?? "";
  const ulid = callback.split("/").pop() || "01JBXR8QW3ZK7YFN2MHTVC4DS6";
  const serverName = hostname(matrix?.homeserver ?? m.identity?.idp.issuer ?? "").replace(/^matrix\./, "");
  return `${header(m, "Matrix Authentication Service (MSC3861 upstream auth)")}http:
  public_base: ${matrix?.mas ?? ""}/
  issuer: ${matrix?.mas ?? ""}/
  listeners:
    - name: web
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: compat
        - name: graphql
        - name: assets
      binds:
        - address: "[::]:8080"
      proxy_protocol: false
    - name: internal
      resources:
        - name: health
      binds:
        - host: localhost
          port: 8081

database:
  uri: postgresql://mas:\${POSTGRES_PASSWORD}@postgres/mas

secrets:
  encryption: \${MAS_ENCRYPTION_SECRET}
  keys:
    - kid: rsa
      key_file: /keys/rsa.pem
    - kid: ec
      key_file: /keys/ec.pem

matrix:
  homeserver: ${serverName}
  secret: \${MAS_SYNAPSE_SHARED_SECRET}
  endpoint: http://synapse:8008

# Synapse authenticates to MAS as this client (MSC3861).
clients:
  - client_id: 0000000000000000000SYNAPSE
    client_auth_method: client_secret_basic
    client_secret: \${MAS_SYNAPSE_SHARED_SECRET}

# The node's own keystone is the ONLY identity source.
passwords:
  enabled: false

account:
  password_registration_enabled: false

upstream_oauth2:
  providers:
    - id: ${ulid}
      issuer: ${m.identity?.idp.issuer ?? ""}
      human_name: "${m.name} ID"
      client_id: "${mx?.id ?? "matrix"}"
      client_secret: "\${MATRIX_CLIENT_SECRET}"
      token_endpoint_auth_method: client_secret_basic
      scope: "${m.identity?.idp.scopes.join(" ") ?? ""}"
      claims_imports:
        subject:
          template: "{{ user.sub }}"
        localpart:
          action: require
          # NEVER user.sub — that is the wallet address, and a Matrix ID is
          # immutable, public in every room, and federates. An address-derived
          # MXID would permanently link a citizen's chat to their onchain
          # balances, votes and holdings. The keystone emits a stable
          # pseudonymous handle for exactly this.
          template: "{{ user.preferred_username }}"
        displayname:
          action: suggest
          template: "{{ user.name }}"
        email:
          action: suggest
          template: "{{ user.email }}"
`;
}

/**
 * Synapse homeserver.yaml.
 *
 * Authentication is fully delegated to MAS (MSC3861) — Synapse itself issues no
 * passwords and no registration. `x_forwarded: true` because Caddy terminates TLS
 * in front; without it every client appears to come from the proxy's IP and rate
 * limiting/abuse controls become meaningless.
 */
export function renderSynapseConfig(m: NetizenManifest): string {
  const matrix = m.services.chat?.matrix;
  const serverName = hostname(matrix?.homeserver ?? "").replace(/^matrix\./, "");
  return `${header(m, "Synapse homeserver")}server_name: "${serverName}"
public_baseurl: "${matrix?.homeserver ?? ""}/"
pid_file: /data/homeserver.pid
report_stats: false
signing_key_path: "/data/signing.key"
media_store_path: /data/media_store

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true          # Caddy terminates TLS in front of us
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    user: synapse
    password: \${POSTGRES_PASSWORD}
    database: synapse
    host: postgres
    cp_min: 5
    cp_max: 10

# Authentication is delegated to MAS. Synapse graduated this out of
# experimental_features.msc3861, which newer builds now REJECT outright
# ("msc3861 was removed"), so the supported stanza is used here.
matrix_authentication_service:
  enabled: true
  endpoint: http://mas:8080/
  secret: "\${MAS_SYNAPSE_SHARED_SECRET}"

password_config:
  enabled: false
enable_registration: false

macaroon_secret_key: "\${SYNAPSE_MACAROON_SECRET}"
form_secret: "\${SYNAPSE_FORM_SECRET}"

trusted_key_servers:
  - server_name: "matrix.org"
suppress_key_server_warning: true
`;
}

/**
 * Generate Matrix secrets + MAS signing keys ON THE BOX, once, appending to .env.
 *
 * Same rule as every other secret on this node: created where they live, never
 * rendered into the bundle, never passed through the CLI. Idempotent — existing
 * values are left untouched so re-running the installer never rotates a key out
 * from under a running homeserver (which would invalidate every session).
 */
export function renderMatrixSecretsScript(): string {
  return `#!/usr/bin/env bash
# Generated by netizen render. Idempotent: only creates what is missing.
set -euo pipefail
cd "$(dirname "$0")/.."
ENV_FILE=./.env
KEYS=./matrix/keys
mkdir -p "$KEYS"

add_secret() {   # add_secret NAME VALUE  — only if NAME is absent
  if ! grep -q "^$1=" "$ENV_FILE" 2>/dev/null; then
    printf '%s=%s\\n' "$1" "$2" >> "$ENV_FILE"
    echo "generated $1"
  fi
}

add_secret MAS_ENCRYPTION_SECRET      "$(openssl rand -hex 32)"
add_secret MAS_SYNAPSE_SHARED_SECRET  "$(openssl rand -hex 32)"
add_secret SYNAPSE_MACAROON_SECRET    "$(openssl rand -hex 32)"
add_secret SYNAPSE_FORM_SECRET        "$(openssl rand -hex 32)"
add_secret SYNAPSE_ADMIN_TOKEN        "$(openssl rand -hex 32)"
chmod 600 "$ENV_FILE"

# MAS signing keys — referenced by path from its config so no key material is
# ever inlined into YAML or into a rendered bundle.
[ -f "$KEYS/rsa.pem" ] || openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$KEYS/rsa.pem" 2>/dev/null
[ -f "$KEYS/ec.pem" ]  || openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:prime256v1 -out "$KEYS/ec.pem" 2>/dev/null
chmod 600 "$KEYS"/*.pem
echo "matrix secrets ready"
`;
}

export function renderNextcloudSetup(m: NetizenManifest): string {
  const nc = rp(m, "nextcloud");
  const ws = m.services.workspace;
  const secret = m.services.secrets?.nextcloudClientSecret ?? "$NEXTCLOUD_CLIENT_SECRET";
  return `#!/usr/bin/env bash
${header(m, "Nextcloud OIDC + group folders (run inside the container)")}set -euo pipefail
php occ app:install user_oidc || true
php occ user_oidc:provider "${m.name}" \\
  --clientid="${nc?.id ?? "nextcloud"}" \\
  --clientsecret="${secret}" \\
  --discoveryuri="${m.identity?.idp.discovery ?? ""}" \\
  --scope="${m.identity?.idp.scopes.join(" ") ?? ""}" \\
  --unique-uid=0 --mapping-uid=sub --mapping-email=email \\
  --mapping-display-name=name --mapping-groups=groups \\
  --check-bearer=1 --bearer-provisioning=1
# --unique-uid=0 makes the Nextcloud uid EQUAL the OIDC sub, which is what makes
# the WebDAV path derivable (the app can build a citizen's DAV root from their
# access token's sub with no extra lookup). Flipping this on a node that already
# has users renumbers every account and orphans their existing home directories
# — safe only on a fresh install, never retrofit onto a running node.
php occ config:app:set user_oidc provisioning_groups --value=1
# Bearer-token API access — how the app reads a citizen's files with their own
# access token rather than a stored password. Needs user_oidc >= 7.4.0.
#
# --check-bearer defaults to 0 when a provider is created, and WITHOUT it the
# provider is never consulted for bearer auth at all: a valid token returns 401
# from every WebDAV/OCS call while every setting reads back correct. That cost
# hours on the live node. --bearer-provisioning=1 creates the Nextcloud account
# on first bearer request, which is what makes a citizen's first file listing
# work without an interactive Nextcloud login.
#
# VERIFIED on the live node: the keystone issues OPAQUE access tokens (panva's
# default — no \`formats\` config), not self-encoded JWTs. \`selfencoded_bearer_
# validation\` validates a self-encoded JWT and would reject every token this
# keystone issues, so it MUST stay off. \`userinfo_bearer_validation\` instead
# calls the keystone's userinfo endpoint to validate the opaque token, which is
# what actually works here. Do not "fix" this back to selfencoded=1 — it was
# tried and breaks every WebDAV/OCS call.
#
# config:system:set, NOT config:app:set. user_oidc reads these through
# getSystemValue('user_oidc', []) — Nextcloud's SYSTEM config. Setting them as
# APP config succeeds, echoes the value back, shows correctly in
# \`occ config:list user_oidc\`, and is never read by the code path that decides
# whether a bearer token is accepted. A setting that confirms itself and does
# nothing is the worst shape a misconfiguration can take; this comment exists so
# nobody re-derives that the hard way.
${ws?.bearerValidation
  ? `php occ config:system:set user_oidc userinfo_bearer_validation --value=true --type=boolean
php occ config:system:set user_oidc selfencoded_bearer_validation --value=false --type=boolean`
  : "# bearerValidation not declared — the app cannot read files via the API"}
php occ app:install groupfolders || true
# One group folder per org (ACL = org:<accountId>:<role>) is provisioned by
# \`netizen up\` from the org registry — idempotent (create-if-absent).
`;
}

export function renderStrfryConf(m: NetizenManifest): string {
  const host = hostname(m.services.chat?.nostr?.relay ?? "");
  return `${header(m, "Nostr relay (strfry)")}db = "/app/strfry-db/"
relay {
  bind = "0.0.0.0"
  port = 7777
  info {
    name = "${m.name} Relay"
    description = "Sovereign community relay for ${m.name}${host ? ` (${host})` : ""}"
  }
  writePolicy { plugin = "/etc/strfry/write-policy.sh" }   # members-only writes (reads open)
}
`;
}

/** Caddy reverse proxy for every service subdomain the manifest declares (auto TLS). */
export function renderCaddyfile(m: NetizenManifest): string {
  const blocks: string[] = [];
  const add = (u: string | undefined, upstream: string) => {
    if (u) blocks.push(`${hostname(u)} {\n  reverse_proxy ${upstream}\n}`);
  };
  // Only route the IdP locally when this node actually hosts it. An externally
  // hosted keystone (e.g. on Fly) resolves via its own DNS/TLS — routing it here
  // would blackhole logins for every service on the node.
  if (m.identity && m.identity.idp.hosted !== "external") add(m.identity.idp.issuer, "roebel-id:3010");
  const ws = m.services.workspace;
  if (ws?.nextcloud && ws.collabora) {
    // Collabora shares the Nextcloud host: its own paths go to the editor, the
    // rest to Nextcloud. Same-origin keeps WOPI simple and needs no extra DNS
    // record or certificate. (Without this the Office app 404s — the editor is
    // running but unreachable.)
    // `handle` blocks are mutually exclusive and evaluated in written order.
    // Two bare `reverse_proxy` directives do NOT preserve order in Caddy — the
    // Collabora paths silently fell through to Nextcloud and Office 404'd.
    blocks.push(`${hostname(ws.nextcloud)} {
  handle /browser/* {
    reverse_proxy collabora:9980
  }
  handle /hosting/* {
    reverse_proxy collabora:9980
  }
  handle /cool/* {
    reverse_proxy collabora:9980
  }
  handle {
    reverse_proxy nextcloud:80
  }
}`);
  } else {
    add(ws?.nextcloud, "nextcloud:80");
  }
  add(ws?.mail, "ox:8080"); // Open-Xchange
  add(ws?.wiki, "xwiki:8080");
  add(ws?.video, "jitsi:8000");
  add(ws?.project, "openproject:80");
  // NOTE: `portal` is a link target for the agent-workspace tile, not a service
  // this installer provisions yet — no Caddy route until something backs it.
  add(m.services.chat?.matrix?.homeserver, "synapse:8008");
  add(m.services.chat?.matrix?.mas, "mas:8080");
  add(m.services.chat?.matrix?.element, "element:80");
  const relay = m.services.chat?.nostr?.relay;
  if (relay) blocks.push(`${hostname(relay)} {\n  reverse_proxy strfry:7777\n}`);
  // The index is public by design: it is how a PEER's agent asks this node a
  // question, and everything in it came off world-readable relays.
  const indexUrl = m.services.indexer?.publicRead;
  if (indexUrl && m.services.metering) {
    // Metering wraps the free API rather than replacing it: paid paths go to
    // the gateway, everything else stays exactly the free indexer. `handle`
    // blocks are order-sensitive — the catch-all MUST come last (same lesson
    // as the Collabora block above).
    blocks.push(`${hostname(indexUrl)} {
  handle /bulk/* {
    reverse_proxy gateway:8402
  }
  handle /export* {
    reverse_proxy gateway:8402
  }
  handle /firehose* {
    reverse_proxy gateway:8402
  }
  handle /pay* {
    reverse_proxy gateway:8402
  }
  handle /metering/* {
    reverse_proxy gateway:8402
  }
  handle {
    reverse_proxy indexer:8080
  }
}`);
  } else if (indexUrl) {
    blocks.push(`${hostname(indexUrl)} {\n  reverse_proxy indexer:8080\n}`);
  }
  // One vhost carries Buzz's WebSocket, REST and media — Caddy upgrades WS
  // transparently, so no extra directives (upstream's own Caddyfile is this line).
  add(m.services.buzz?.url, "buzz:3000");
  return header(m, "Caddy reverse proxy (auto TLS)") + "\n" + blocks.join("\n\n") + "\n";
}

/** The deployable stack — every service this node declares, and nothing else. */
export function renderComposeYml(m: NetizenManifest): string {
  const hasMatrix = !!m.services.chat?.matrix;
  const hasNostr = !!m.services.chat?.nostr;
  // An externally hosted keystone (identity.idp.hosted === "external") is NOT
  // provisioned here: starting a second one would shadow the real issuer.
  const hostsIdp = !!m.identity && m.identity.idp.hosted !== "external";
  const svc: string[] = [
    `  caddy:
    image: caddy:2
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes: ["./Caddyfile:/etc/caddy/Caddyfile", "caddy_data:/data"]`,
  ];
  if (hostsIdp) {
    svc.push(`  roebel-id:
    image: \${ROEBEL_ID_IMAGE:-ghcr.io/roebel-labs/roebel-id:latest}
    restart: unless-stopped
    env_file: ["./roebel-id.env"]
    expose: ["3010"]`);
  }
  if (hasMatrix) {
    svc.push(
      `  postgres:
    image: postgres:16
    restart: unless-stopped
    environment: { POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD}" }
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "./postgres/init:/docker-entrypoint-initdb.d:ro"`,
      `  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    volumes:
      - "synapse_data:/data"
      - "./synapse/homeserver.rendered.yaml:/data/homeserver.yaml:ro"
    depends_on: [postgres, mas]
    expose: ["8008"]`,
      `  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:latest
    restart: unless-stopped
    command: ["server", "--config", "/config.yaml"]
    volumes:
      - "./mas/config.rendered.yaml:/config.yaml:ro"
      - "./matrix/keys:/keys:ro"
    depends_on: [postgres]
    expose: ["8080"]`,
      `  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes: ["./element/config.json:/app/config.json"]
    expose: ["80"]`,
    );
  }
  if (hasNostr) {
    // The relay mounts the POLICY DIRECTORY (not single files): editors/sed -i
    // replace inodes, and a single-file bind mount would keep the stale inode,
    // so live grants/revokes of the write allow-list would silently not apply.
    svc.push(
      `  strfry:
    image: ghcr.io/hoytech/strfry:latest
    restart: unless-stopped
    command: relay
    volumes:
      - "./strfry.conf:/etc/strfry.conf"
      - "./strfry-policy:/etc/strfry:ro"
      - "strfry_db:/app/strfry-db"
    expose: ["7777"]`,
    );
    // The allow-list syncer: on-chain CitizenNFT membership -> relay write access,
    // so admission and revocation are automatic rather than a hand-run script.
    // It mounts the SAME policy directory as the relay but WRITABLE (the relay
    // gets :ro), and it only reaches out — no inbound surface added to the box.
    if (m.services.backend && m.contracts) {
      const agentKeys = m.agents?.a2a?.relayPubkeys ?? [];
      svc.push(
        `  relay-sync:
    image: node:22-alpine
    restart: unless-stopped
    command: ["node", "/app/relay-sync.cjs"]
    volumes:
      - "./relay-sync/relay-sync.cjs:/app/relay-sync.cjs:ro"
      - "./strfry-policy:/etc/strfry"
    environment:
      SUPABASE_URL: "\${SUPABASE_URL}"
      # Service-role key: reads the private wallet<->npub registry. Never in the
      # bundle or in git — it comes from the box's own .env.
      SUPABASE_SERVICE_KEY: "\${SUPABASE_SERVICE_KEY}"
      GNOSIS_RPC_URL: "\${GNOSIS_RPC}"
      CITIZEN_NFT_ADDRESS: "${m.contracts!.citizenNft}"
      ALLOWLIST_PATH: "/etc/strfry/members.txt"
      SYNC_INTERVAL_SECONDS: "300"
      # This node's own agents. Their key is NIP-06 derived from an agent smart
      # account holding no CitizenNFT, so without this the syncer would erase
      # them every pass and no agent could publish to its own community's relay.
      AGENT_PUBKEYS: "${agentKeys.join(",")}"${
        m.services.publisher
          ? `\n      # Publisher-derived org identities join the allow-list every pass.\n      EXTRA_KEYS_FILE: "/etc/strfry/publisher-keys.txt"`
          : ""
      }
    depends_on: [strfry]`,
      );
    }

    // The public-data publisher: Supabase public datasets -> signed replaceable
    // events on the relay, each under a node-held per-organisation identity.
    // Needs the node secret (identity root) and the service key (dataset read),
    // and shares the policy dir so relay-sync can merge its derived pubkeys.
    if (hasNostr && m.services.publisher && m.services.backend) {
      const pub = m.services.publisher;
      svc.push(
        `  publisher:
    image: node:22-alpine
    restart: unless-stopped
    command: ["node", "/app/publisher.cjs"]
    volumes:
      - "./publisher/publisher.cjs:/app/publisher.cjs:ro"
      - "./strfry-policy:/etc/strfry"
      - "media_data:/media"
    environment:
      NODE_ID: "${m.id}"
      RELAY_URL: "ws://strfry:7777"
      PUBLISH_DATASETS: "${pub.datasets.join(",")}"
      PUBLISH_INTERVAL_SECONDS: "${pub.intervalSeconds ?? 300}"
      PUBLISHER_KEYS_FILE: "/etc/strfry/publisher-keys.txt"
      MEDIA_DIR: "/media"${m.services.indexer?.publicRead ? `\n      MEDIA_PUBLIC_BASE: "${m.services.indexer.publicRead}"` : ""}${pub.backfeed ? `\n      BACKFEED: "true"` : ""}
      SUPABASE_URL: "\${SUPABASE_URL}"
      SUPABASE_SERVICE_KEY: "\${SUPABASE_SERVICE_KEY}"
      NODE_AGENT_SECRET: "\${NODE_AGENT_SECRET}"
    depends_on: [strfry]`,
      );
    }

    // NSP-10: the cross-node query layer. Indexes this node's OWN relay and its
    // federation mirror, so a question can span both. Needs Postgres, which the
    // stack already runs.
    if (m.services.indexer && m.services.backend) {
      const idx = m.services.indexer;
      const sources = [
        { nodeId: m.id, relay: "ws://strfry:7777", kinds: idx.kinds },
        ...(m.peers?.length ? [{ nodeId: "peers", relay: "ws://mirror:7777", kinds: idx.kinds }] : []),
      ];
      svc.push(
        `  indexer:
    image: node:22-alpine
    restart: unless-stopped
    command: ["node", "/app/indexer.cjs"]
    volumes:
      - "./indexer/indexer.cjs:/app/indexer.cjs:ro"
      - "./manifest.json:/app/manifest.json:ro"
      - "media_data:/media"
    environment:
      NODE_ID: "${m.id}"
      MANIFEST_PATH: "/app/manifest.json"
      MEDIA_DIR: "/media"
      DATABASE_URL: "postgres://indexer:\${POSTGRES_PASSWORD}@postgres:5432/indexer"
      SOURCES: '${JSON.stringify(sources)}'
      INGEST_INTERVAL_SECONDS: "${idx.ingestIntervalSeconds ?? 120}"
      PORT: "8080"
    expose: ["8080"]
    depends_on: [postgres, strfry]`,
      );
    }

    // Metered machine-scale access (x402): the facilitator verifies + settles
    // EIP-3009 payments on this node's own chain; the gateway serves the paid
    // endpoints and shares the indexer's database (the ledger lives beside the
    // index it meters). Secrets: only the settler's gas key — it cannot
    // redirect funds, the payer's signature fixes payTo.
    if (m.services.metering && m.services.indexer && m.services.backend && m.chain) {
      const met = m.services.metering;
      const rpc = typeof m.chain.rpc === "string" && m.chain.rpc.startsWith("$")
        ? `\${${m.chain.rpc.slice(1)}}`
        : String(m.chain.rpc);
      svc.push(
        `  facilitator:
    image: node:22-alpine
    restart: unless-stopped
    command: ["node", "/app/facilitator.cjs"]
    volumes:
      - "./facilitator/facilitator.cjs:/app/facilitator.cjs:ro"
    environment:
      NETWORK: "${met.network}"
      RPC_URL: "${rpc}"
      # Gas-only key. It submits payer-signed authorizations; value moves
      # payer->treasury regardless of who submits.
      SETTLER_PRIV: "\${METERING_SETTLER_PRIV}"
      PORT: "8402"
    expose: ["8402"]`,
        `  gateway:
    image: node:22-alpine
    restart: unless-stopped
    command: ["node", "/app/gateway.cjs"]
    volumes:
      - "./gateway/gateway.cjs:/app/gateway.cjs:ro"
      - "./strfry-policy:/etc/strfry:ro"
    environment:
      NODE_ID: "${m.id}"
      PUBLIC_BASE: "${m.services.indexer.publicRead ?? ""}"
      DATABASE_URL: "postgres://indexer:\${POSTGRES_PASSWORD}@postgres:5432/indexer"
      FACILITATOR_URL: "http://facilitator:8402"
      PAY_TO: "${met.payTo}"
      NETWORK: "${met.network}"
      ASSET: "${met.asset}"
      ASSET_NAME: ${JSON.stringify(met.assetName)}
      ASSET_VERSION: "${met.assetVersion}"
      ASSET_DECIMALS: "${met.assetDecimals}"
      PRICE_BULK: "${met.prices.bulk}"
      PRICE_EXPORT: "${met.prices.export}"
      PRICE_FIREHOSE_DAY: "${met.prices.firehoseDay}"
      SPLIT_AUTHORS: "${met.split.authors ?? 0}"
      EXCLUDED_FILE: "/etc/strfry/metering-excluded.txt"
      PORT: "8402"
    expose: ["8402"]
    depends_on: [postgres, facilitator]`,
      );
    }

    // NSP-6: the node's mention-answering agent, as a declared service. Secrets
    // come from the box's .env via compose interpolation — never from the
    // manifest, which is public. Only the two the watcher actually needs are
    // passed, deliberately NOT the whole .env: the hand-rolled predecessor used
    // --env-file and handed the agent the Supabase service key with it.
    if (hasNostr && m.agents?.watcher) {
      const w = m.agents.watcher;
      const optional = [
        w.displayName ? `      AGENT_DISPLAY_NAME: ${JSON.stringify(w.displayName)}` : "",
        w.model ? `      ANTHROPIC_MODEL: "${w.model}"` : "",
        w.perAuthorPerHour ? `      AGENT_PER_AUTHOR_PER_HOUR: "${w.perAuthorPerHour}"` : "",
        w.perDay ? `      AGENT_PER_DAY: "${w.perDay}"` : "",
      ].filter(Boolean);
      svc.push(
        `  agent-watcher:
    image: node:22-alpine
    restart: unless-stopped
    command: ["node", "/app/agent-watcher.cjs"]
    volumes:
      - "./agent-watcher/agent-watcher.cjs:/app/agent-watcher.cjs:ro"
    environment:
      NODE_ID: "${m.id}"
      NODE_NAME: ${JSON.stringify(m.name)}
      AGENT_NAME: "${w.agent}"
      RELAY_URL: "ws://strfry:7777"
      ANTHROPIC_API_KEY: "\${ANTHROPIC_API_KEY}"
      NODE_AGENT_SECRET: "\${NODE_AGENT_SECRET}"${optional.length ? "\n" + optional.join("\n") : ""}
    depends_on: [strfry]`,
      );
    }

    // NSP-9 federation: mirror declared peers' public events over NIP-77
    // negentropy. Runs `strfry sync` inside the relay's own container image so it
    // shares the binary and the store; pull-based, so no inbound surface is added.
    if (m.peers?.length) {
      // The mirror is a SEPARATE store from the authoring relay, so federating
      // never weakens the members-only write gate. It serves reads; its content
      // arrives only from the syncer beside it.
      svc.push(
        `  mirror:
    image: ghcr.io/hoytech/strfry:latest
    restart: unless-stopped
    command: relay
    entrypoint: ["/app/strfry", "--config=/etc/strfry-mirror/mirror.conf"]
    volumes:
      - "./strfry-mirror:/etc/strfry-mirror:ro"
      - "mirror_db:/app/mirror-db"
    expose: ["7777"]`,
        `  federation:
    image: ghcr.io/hoytech/strfry:latest
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/etc/strfry-mirror/sync-peers.sh"]
    volumes:
      - "./strfry-mirror:/etc/strfry-mirror:ro"
      - "./strfry-mirror/mirror-sync.conf:/etc/strfry-mirror-sync.conf:ro"
      - "mirror_db:/app/mirror-db"
    depends_on: [mirror]`,
      );
    }

    // Vanish pipeline: NIP-62 requests (and mirror-side NIP-09 deletes, where
    // strfry's native ingest handling is not guaranteed for sync-written
    // events) become REAL LMDB deletion. Two halves on purpose: the scanner
    // (node) does all JSON parsing and NIP-09 ownership verification; the
    // executor (strfry image) only ever sees fixed-shape, re-validated hex
    // and runs `strfry delete`. This is what makes the Datenschutzerklärung's
    // "deletion requests are honoured in our own systems" true on the relay
    // itself, not just in Supabase (DSGVO_AI_ACT_COMPLIANCE.md §2.1).
    {
      const nostrRelay = m.services.chat?.nostr?.relay ?? "";
      const mirrorEnv = m.peers?.length ? `\n      MIRROR_WS: "ws://mirror:7777"` : "";
      const mirrorMounts = m.peers?.length
        ? `\n      - "./strfry-mirror/mirror-sync.conf:/etc/strfry-mirror-sync.conf:ro"\n      - "mirror_db:/app/mirror-db"`
        : "";
      svc.push(
        `  vanish-scan:
    image: node:22-alpine
    restart: unless-stopped
    command: ["node", "/app/vanish-scan.cjs"]
    volumes:
      - "./vanish/vanish-scan.cjs:/app/vanish-scan.cjs:ro"
      - "vanish_queue:/vanish"
    environment:
      AUTH_WS: "ws://strfry:7777"${mirrorEnv}
      PUBLIC_RELAY_URLS: "${nostrRelay}"
      SCAN_INTERVAL_SECONDS: "300"
    depends_on: [strfry]`,
        `  vanish-exec:
    image: ghcr.io/hoytech/strfry:latest
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/etc/strfry-vanish/vanish-exec.sh"]
    volumes:
      - "./strfry-vanish:/etc/strfry-vanish:ro"
      - "./strfry.conf:/etc/strfry.conf:ro"
      - "strfry_db:/app/strfry-db"
      - "vanish_queue:/vanish"${mirrorMounts}
    depends_on: [strfry]`,
      );
    }
  }

  // ---- Workspace (the openDesk-equivalent suite). Each is provisioned only
  // when the manifest declares its URL, so every node picks its own subset.
  const ws = m.services.workspace;
  if (ws?.nextcloud) {
    svc.push(
      `  nextcloud:
    image: nextcloud:stable
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${hostname(ws.nextcloud)}"
      OVERWRITEPROTOCOL: https
    volumes: ["nextcloud_data:/var/www/html"]
    depends_on: [postgres]
    expose: ["80"]`,
    );
    if (ws.collabora) {
      // Every declared WOPI host — the app's own origin(s) that embed this
      // Collabora, alongside Nextcloud's own host — goes into the alias group.
      // Without the app's origin here, Collabora refuses to render its
      // documents for it.
      const aliases = [`https://${hostname(ws.nextcloud)}`, ...(ws.wopiHosts ?? [])];
      svc.push(
        `  collabora:
    image: collabora/code:latest
    restart: unless-stopped
    environment:
${aliases.map((alias, i) => `      aliasgroup${i + 1}: "${alias}"`).join("\n")}
      DONT_GEN_SSL_CERT: "true"
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
    expose: ["9980"]`,
      );
    }
  }
  if (ws?.mail) {
    svc.push(
      `  ox:                      # Open-Xchange (mail/calendar/contacts)
    image: \${OX_IMAGE:-openexchange/appsuite:latest}
    restart: unless-stopped
    depends_on: [postgres]
    expose: ["8080"]
    # NOTE: OX needs an IMAP/SMTP backend + its own provisioning — see PLAN.md`,
    );
  }
  if (ws?.wiki) {
    svc.push(
      `  xwiki:
    image: xwiki:stable-postgres-tomcat
    restart: unless-stopped
    environment:
      DB_USER: xwiki
      DB_PASSWORD: "\${POSTGRES_PASSWORD}"
      DB_HOST: postgres
    volumes: ["xwiki_data:/usr/local/xwiki"]
    depends_on: [postgres]
    expose: ["8080"]`,
    );
  }
  if (ws?.video) {
    svc.push(
      `  jitsi:                   # single-container Jitsi Meet (web + prosody + jicofo + jvb)
    image: jitsi/web:stable
    restart: unless-stopped
    environment:
      PUBLIC_URL: "${ws.video}"
      ENABLE_AUTH: "1"
      AUTH_TYPE: jwt          # tokens minted from the Röbel ID session
    expose: ["80"]
    # NOTE: full Jitsi needs prosody/jicofo/jvb sidecars + UDP 10000 — see PLAN.md`,
    );
  }
  if (ws?.project) {
    svc.push(
      `  openproject:
    image: openproject/openproject:14
    restart: unless-stopped
    environment:
      OPENPROJECT_HOST__NAME: "${hostname(ws.project)}"
      OPENPROJECT_HTTPS: "true"
      DATABASE_URL: "postgres://openproject:\${POSTGRES_PASSWORD}@postgres/openproject"
    volumes: ["openproject_data:/var/openproject/assets"]
    depends_on: [postgres]
    expose: ["80"]`,
    );
  }

  // ---- Sovereign AI gateway (model routing; keeps egress under node policy).
  if (m.ai?.selfHosted) {
    svc.push(
      `  litellm:                 # AI gateway — routes models, enforces data-egress policy
    image: ghcr.io/berriai/litellm:main-latest
    restart: unless-stopped
    env_file: ["./.env"]
    volumes: ["./ai/litellm.yaml:/app/config.yaml"]
    command: ["--config", "/app/config.yaml"]
    expose: ["4000"]`,
    );
  }

  // ---- Line B: the agentic workspace (stock block/buzz, upstream's own bundle
  // shape — deploy/compose/ at the pinned tag). Sidecars carry a buzz- prefix
  // because `postgres` already names the node's shared database on this compose
  // network, and Buzz's Postgres is 17 while the shared one is 16. Data lives in
  // named volumes, so `netizen up`'s rsync --delete never touches it.
  const buzz = m.services.buzz;
  if (buzz) {
    const bhost = hostname(buzz.url);
    // Compose-side interpolation resolves the manifest's own ref name; vault:
    // refs have no compose story and must fail at render time, not on the box.
    const bref = (ref: string, what: string): string => {
      if (!ref.startsWith("$"))
        throw new Error(`services.buzz.secrets.${what}: the compose renderer needs a $ENV_VAR ref (vault refs are not resolvable in docker-compose)`);
      return ref.slice(1);
    };
    const pg = bref(buzz.secrets.postgresPassword, "postgresPassword");
    const redis = bref(buzz.secrets.redisPassword, "redisPassword");
    const s3a = bref(buzz.secrets.s3AccessKey, "s3AccessKey");
    const s3s = bref(buzz.secrets.s3SecretKey, "s3SecretKey");
    const relayKey = bref(buzz.secrets.relayPrivateKey, "relayPrivateKey");
    const hmac = bref(buzz.secrets.gitHookHmac, "gitHookHmac");
    svc.push(
      `  buzz:                    # line B agentic workspace — stock block/buzz relay
    image: ghcr.io/block/buzz:${buzz.imageTag}
    restart: unless-stopped
    environment:
      BUZZ_BIND_ADDR: "0.0.0.0:3000"
      BUZZ_HEALTH_PORT: "8080"
      BUZZ_METRICS_PORT: "9102"
      DATABASE_URL: "postgres://buzz:\${${pg}}@buzz-postgres:5432/buzz"
      REDIS_URL: "redis://:\${${redis}}@buzz-redis:6379"
      BUZZ_S3_ENDPOINT: "http://buzz-minio:9000"
      # Docker DNS resolves \`buzz-minio\`, not \`<bucket>.buzz-minio\` — path style.
      BUZZ_S3_ADDRESSING_STYLE: "path"
      BUZZ_S3_ACCESS_KEY: "\${${s3a}}"
      BUZZ_S3_SECRET_KEY: "\${${s3s}}"
      BUZZ_S3_BUCKET: "buzz-media"
      BUZZ_GIT_REPO_PATH: "/data/git"
      # Embedded SQLx migrations run at boot — first boot creates the schema,
      # later boots no-op. Without this a fresh node needs a hand-run migrate.
      BUZZ_AUTO_MIGRATE: "true"
      BUZZ_DOMAIN: "${bhost}"
      RELAY_URL: "wss://${bhost}"
      BUZZ_MEDIA_BASE_URL: "https://${bhost}/media"
      BUZZ_MEDIA_SERVER_DOMAIN: "${bhost}"
      BUZZ_CORS_ORIGINS: "https://${bhost}"
      # Closed-relay mode: the relay IS the membership boundary (NIP-42 + NIP-43).
      BUZZ_REQUIRE_AUTH_TOKEN: "true"
      BUZZ_REQUIRE_RELAY_MEMBERSHIP: "true"
      BUZZ_ALLOW_NIP_OA_AUTH: "true"
      RELAY_OWNER_PUBKEY: "${buzz.ownerPubkey}"
      BUZZ_RELAY_PRIVATE_KEY: "\${${relayKey}}"
      BUZZ_GIT_HOOK_HMAC_SECRET: "\${${hmac}}"
    volumes: ["buzz_git_data:/data/git"]
    expose: ["3000"]
    depends_on:
      buzz-postgres: { condition: service_healthy }
      buzz-redis: { condition: service_healthy }
      buzz-minio-init: { condition: service_completed_successfully }
    # Probe /_readiness over /dev/tcp — the runtime image has bash but no curl.
    healthcheck:
      test: ["CMD-SHELL", "bash -ec 'exec 3<>/dev/tcp/127.0.0.1/8080; printf \\"GET /_readiness HTTP/1.1\\\\r\\\\nHost: 127.0.0.1\\\\r\\\\nConnection: close\\\\r\\\\n\\\\r\\\\n\\" >&3; grep -q \\"200 OK\\" <&3'"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 30s`,
      `  buzz-postgres:           # Buzz's own database — postgres 17, never the shared 16
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: buzz
      POSTGRES_USER: buzz
      POSTGRES_PASSWORD: "\${${pg}}"
    volumes: ["buzz_pg_data:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buzz -d buzz"]
      interval: 5s
      timeout: 5s
      retries: 12`,
      `  buzz-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "\${${redis}}"]
    volumes: ["buzz_redis_data:/data"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \\"\${${redis}}\\" ping | grep -q PONG"]
      interval: 5s
      timeout: 3s
      retries: 12`,
      `  buzz-minio:              # Blossom/S3 media store
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    command: ["server", "/data"]
    environment:
      MINIO_ROOT_USER: "\${${s3a}}"
      MINIO_ROOT_PASSWORD: "\${${s3s}}"
    volumes: ["buzz_minio_data:/data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 12`,
      `  buzz-minio-init:         # one-shot: create the media bucket, deny anonymous
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      buzz-minio: { condition: service_healthy }
    environment:
      BUZZ_S3_ACCESS_KEY: "\${${s3a}}"
      BUZZ_S3_SECRET_KEY: "\${${s3s}}"
    entrypoint: >
      /bin/sh -euc '
        mc alias set local http://buzz-minio:9000 "$\${BUZZ_S3_ACCESS_KEY}" "$\${BUZZ_S3_SECRET_KEY}"
        mc mb --ignore-existing "local/buzz-media"
        mc anonymous set none "local/buzz-media"
      '
    restart: "no"`,
    );

    // Resident agents (Autar M1): one 24/7 harness container per declared
    // agent, under the agent's canonical manifest-declared identity. Internal
    // relay URL on purpose — a resident agent must not depend on public DNS to
    // reach a service three containers away. Removing the entry + `netizen up`
    // stops the runtime; relay-membership revocation is buzz-admin's job.
    for (const agent of buzz.acpAgents ?? []) {
      const priv = bref(agent.privateKey, `acpAgents.${agent.name}.privateKey`);
      const model = bref(agent.anthropicApiKey, `acpAgents.${agent.name}.anthropicApiKey`);
      svc.push(`  buzz-acp-${agent.name}:      # resident agent "${agent.name}" — 24/7 ACP harness
    image: ${agent.image}
    restart: unless-stopped
    environment:
      BUZZ_PRIVATE_KEY: "\${${priv}}"
      BUZZ_RELAY_URL: "ws://buzz:3000"
      BUZZ_ACP_AGENT_COMMAND: "claude-agent-acp"
      ANTHROPIC_API_KEY: "\${${model}}"
    working_dir: /workspace
    volumes: ["buzz_acp_${agent.name}_data:/workspace"]
    depends_on:
      buzz: { condition: service_healthy }`);
    }
  }

  // Postgres backs Matrix, Nextcloud, XWiki, OpenProject and the indexer. Ask the
  // one function that owns that list, so this cannot drift from the databases
  // `postgresDatabases()` actually creates (it did: the indexer got a database
  // but no container).
  // (hasMatrix already emitted postgres above; append it here for the other cases.
  // Order within `services:` is irrelevant to compose — depends_on drives startup.)
  if (composeNeedsPostgres(m) && !hasMatrix) {
    svc.push(`  postgres:
    image: postgres:16
    restart: unless-stopped
    environment: { POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD}" }
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "./postgres/init:/docker-entrypoint-initdb.d:ro"`);
  }

  const vols = ["caddy_data:"];
  if (composeNeedsPostgres(m)) vols.push("pg_data:");
  // Buzz's state is entirely in named volumes — that is what lets `netizen up`
  // rsync --delete the bundle dir without ever touching workspace data.
  if (buzz) vols.push("buzz_git_data:", "buzz_pg_data:", "buzz_redis_data:", "buzz_minio_data:");
  // Each resident agent keeps its working memory the same way.
  for (const a of buzz?.acpAgents ?? []) vols.push(`buzz_acp_${a.name}_data:`);
  if (hasNostr) vols.push("strfry_db:");
  // The vanish work queue: scanner writes, executor drains. Named volume so a
  // container restart never loses a pending deletion request.
  if (hasNostr) vols.push("vanish_queue:");
  // The federation mirror keeps its own store: peers' events never mingle with
  // what this node's own members authored.
  if (hasNostr && m.peers?.length) vols.push("mirror_db:");
  // Content-addressed media shared between publisher (writes) and indexer (serves).
  if (hasNostr && m.services.publisher) vols.push("media_data:");
  if (hasMatrix) vols.push("synapse_data:");
  if (ws?.nextcloud) vols.push("nextcloud_data:");
  if (ws?.wiki) vols.push("xwiki_data:");
  if (ws?.project) vols.push("openproject_data:");

  return `# Generated by \`netizen render\` — the sovereign node stack for "${m.id}".
# One command brings up everything this node declares: identity, comms, workspace,
# and AI. Services appear only when the manifest declares them.
# Secrets come from ./.env (see SECRETS.md) — never from this file.
services:
${svc.join("\n")}
volumes:
${vols.map((v) => `  ${v}`).join("\n")}
`;
}

/**
 * The Nostr write policy — CitizenNFT-gated. Rendered by the installer so every
 * node gets the same members-only relay without hand-wiring it (reads stay open).
 * Mirrors packages/cli/policies/nostr-citizen-write/.
 */
export function renderNostrPolicyAwk(m: NetizenManifest): string {
  return `# Generated by \`netizen render\` — write policy for node "${m.id}".
# Accept an EVENT only if its author pubkey is in the members allow-list.
# Re-reads the list per event (live grants/revokes) and fflush()es so strfry
# never blocks on a buffered pipe. Reads are unaffected.
{
  line = $0
  if (!match(line, /"id":"[0-9a-fA-F]{64}"/)) next
  id = substr(line, RSTART + 6, 64)
  pk = ""
  if (match(line, /"pubkey":"[0-9a-fA-F]{64}"/)) pk = tolower(substr(line, RSTART + 10, 64))
  allowed = 0
  if (pk != "") {
    while ((getline p < "/etc/strfry/members.txt") > 0) {
      gsub(/[ \\t\\r\\n]/, "", p)
      if (p != "" && substr(p, 1, 1) != "#" && tolower(p) == pk) { allowed = 1; break }
    }
    close("/etc/strfry/members.txt")
  }
  if (allowed)
    printf("{\\"id\\":\\"%s\\",\\"action\\":\\"accept\\"}\\n", id)
  else
    printf("{\\"id\\":\\"%s\\",\\"action\\":\\"reject\\",\\"msg\\":\\"blocked: only ${m.name} members may publish to this relay\\"}\\n", id)
  fflush()
}
`;
}

export function renderNostrPolicyWrapper(): string {
  return `#!/bin/sh\nexec awk -f /etc/strfry/policy.awk\n`;
}

export function renderNostrMembers(m: NetizenManifest): string {
  const cred = m.identity?.membership.credential ?? "members";
  return `# ${m.name} — Nostr write allow-list. One lowercase 64-hex pubkey per line.
# Populated from ${cred} holders: derive each member's Nostr key from their wallet
# (NIP-06 style, Schnorr != ECDSA so it is a DERIVED key), verify they hold the
# credential on chain, then add the pubkey here. Reads are always open.
# Grant: add-member.sh <pubkey>   Revoke: delete the line. Both take effect live.
`;
}

export function renderNostrAddMember(): string {
  return `#!/bin/sh
# Usage: add-member.sh <64-hex-nostr-pubkey>  — grant write access (live, no restart)
pk="$1"
echo "$pk" | grep -qiE '^[0-9a-f]{64}$' || { echo "not a 64-hex nostr pubkey: $pk" >&2; exit 1; }
f="$(dirname "$0")/members.txt"
grep -qi "^\${pk}$" "$f" 2>/dev/null || printf '%s\\n' "$pk" >> "$f"
echo "granted write: $pk"
`;
}

/** The monetization opt-out list: one hex pubkey per line. An author here is
 *  dropped from every PAID response; their events stay on the free record. */
export function renderMeteringExcluded(m: NetizenManifest): string {
  return header(m, "Metering exclusion list — authors who opted out of monetization") +
    "# One 64-hex Nostr pubkey per line. '#' comments. Re-read every 60s.\n" +
    "# An excluded author's events never appear in /bulk, /export or /firehose\n" +
    "# and never accrue earnings. The free public record is unaffected.\n";
}

/**
 * Manifest-declared agents → Buzz relay membership. Each declared pubkey becomes
 * a relay-signed kind:13534 membership event via `buzz-admin add-member` inside
 * the relay container (which already holds BUZZ_RELAY_PRIVATE_KEY). Declaring the
 * key in the manifest IS the authorization — a grant or revocation is a
 * reviewable git diff, the same rule as agents.a2a.relayPubkeys. Idempotent:
 * re-adding an existing member is a no-op upstream.
 */
export function renderBuzzAddMembers(m: NetizenManifest): string {
  const keys = m.services.buzz?.agentPubkeys ?? [];
  return `#!/bin/sh
# Generated by \`netizen render\` — manifest-declared Buzz agent members.
# Run from the bundle root after the stack is up: sh buzz/add-members.sh
set -eu
cd "$(dirname "$0")/.."
${keys.map((pk) => `docker compose exec -T buzz buzz-admin add-member --pubkey "${pk}"`).join("\n")}
echo "buzz: ${keys.length} manifest-declared agent member(s) ensured"
`;
}

/**
 * Postgres bootstrap. The image only creates the default superuser; every service
 * that shares this database (Nextcloud, Synapse, XWiki, OpenProject) needs its OWN
 * role and database, or it fails with "password authentication failed for user X".
 * Runs once, on first initialisation of an empty data directory.
 */
/**
 * NSP-9 peer sync loop.
 *
 * One `strfry sync` per declared peer, on a loop. Negentropy (NIP-77) reconciles
 * SETS rather than streaming a log, so each pass transfers only the difference —
 * cost tracks what changed, not how much history exists — and a bidirectional
 * link cannot ping-pong, because an event either is in the store or is not.
 *
 * Filters are per-link: a peer carries exactly the kinds its manifest entry
 * declares, so widening what crosses the boundary is always a visible edit.
 *
 * A failing peer must never stop the others: an unreachable node is a normal
 * condition in a federation, not an error worth halting a sweep for.
 */
export function renderFederationSync(m: NetizenManifest, intervalSeconds = 300): string {
  const peers = m.peers ?? [];
  const lines = peers.map((p) => {
    const filter = JSON.stringify({ kinds: p.kinds });
    return [
      `  echo "[$(date -u +%FT%TZ)] pull ${p.id} ${p.relay}"`,
      `  /app/strfry --config=/etc/strfry-mirror-sync.conf sync "${p.relay}" \\`,
      `    --dir down --filter '${filter}' \\`,
      `    || echo "[$(date -u +%FT%TZ)] peer ${p.id} unreachable — continuing"`,
    ].join("\n");
  });

  return `#!/bin/sh
# Generated by \`netizen render\` — NSP-9 federation for node "${m.id}".
#
# Pulls the PUBLIC record of declared peers into this node's federation MIRROR,
# which is a separate store from the members-only authoring relay. Two reasons:
#
#  1. \`strfry sync\` enforces the destination's write policy (verified 2026-07-28:
#     a synced event arrives as sourceType IP4 and is indistinguishable from a
#     stranger publishing). Writing peers into the authoring relay would mean
#     weakening the members-only gate that relay exists to enforce.
#  2. PULL-ONLY: this node never writes into a peer's database. Each node decides
#     what it ingests, and both ends still converge on the same set.
#
# Every peer and kind comes from the manifest. This file is never where trust is
# edited. The binary is addressed absolutely: it is not on PATH in this image.
set -u

while true; do
${lines.join("\n") || '  echo "no peers declared"'}
  sleep ${intervalSeconds}
done
`;
}

/**
 * The vanish executor — drains the deletion work queue into `strfry delete`.
 *
 * The scanner (vanish-scan.cjs) has already done everything that requires
 * judgement: JSON parsing, NIP-62 relay-tag addressing, NIP-09 ownership
 * verification. This script trusts NOTHING anyway: every field is re-validated
 * as fixed-shape hex/digits before it may reach a command line, because a
 * deletion routine steerable by event content would delete other people's
 * record. Failed or invalid lines are logged and skipped forward (marked
 * done) — the queue file itself is append-only and keeps everything, so an
 * operator can replay after fixing the cause by truncating done.log.
 */
export function renderVanishExecutor(m: NetizenManifest): string {
  return `#!/bin/sh
# Generated by \`netizen render\` — vanish executor for node "${m.id}".
#
# Turns NIP-62 "request to vanish" (and verified mirror-side NIP-09) work into
# real LMDB deletion. The scanner beside it wrote the queue after verifying
# ownership; this script re-validates shape and shells out to strfry delete.
# An unsupported \`strfry delete\` is loudly logged — upgrade strfry, then
# truncate done.log to replay the queue.
set -u

Q=/vanish/queue.log
DONE=/vanish/done.log
touch "$Q" "$DONE"

if ! /app/strfry delete --help >/dev/null 2>&1; then
  echo "[vanish-exec] WARNING: this strfry build lacks 'delete' — requests will be marked done but NOT executed (see header)"
fi

conf_for() {
  case "$1" in
    auth) echo "/etc/strfry.conf" ;;
    mirror) echo "/etc/strfry-mirror-sync.conf" ;;
    *) echo "" ;;
  esac
}

hex_ok() {
  case "$1" in
    *[!0-9a-f]*) return 1 ;;
  esac
  [ \${#1} -eq 64 ]
}

while true; do
  done_n=$(wc -l < "$DONE")
  total_n=$(wc -l < "$Q")
  if [ "$total_n" -gt "$done_n" ]; then
    tail -n +"$((done_n + 1))" "$Q" | while IFS=' ' read -r op store a b; do
      conf=$(conf_for "\${store:-}")
      ok=0
      if [ -n "$conf" ] && [ -f "$conf" ]; then
        case "\${op:-}" in
          author)
            if hex_ok "\${a:-}" && [ -n "\${b:-}" ] && [ -z "$(printf %s "$b" | tr -d 0-9)" ]; then
              echo "[vanish-exec] $store: purge author $a until $b"
              /app/strfry --config="$conf" delete --filter "{\\"authors\\":[\\"$a\\"],\\"until\\":$b}" \\
                && ok=1 || echo "[vanish-exec] delete FAILED on $store for author $a"
            fi
            ;;
          ids)
            valid=1
            ids_json=""
            OLDIFS=$IFS; IFS=','
            for id in \${a:-}; do
              hex_ok "$id" || valid=0
              ids_json="\${ids_json:+$ids_json,}\\"$id\\""
            done
            IFS=$OLDIFS
            if [ "$valid" -eq 1 ] && [ -n "$ids_json" ]; then
              echo "[vanish-exec] $store: delete ids $a"
              /app/strfry --config="$conf" delete --filter "{\\"ids\\":[$ids_json]}" \\
                && ok=1 || echo "[vanish-exec] delete FAILED on $store for ids"
            fi
            ;;
        esac
      fi
      [ "$ok" -eq 1 ] || echo "[vanish-exec] line skipped (invalid or failed): \${op:-} \${store:-} \${a:-} \${b:-}"
      printf '%s\\n' "\${op:-} \${store:-} \${a:-} \${b:-}" >> "$DONE"
    done
  fi
  sleep 60
done
`;
}

/**
 * The federation mirror's relay config — serves READS of peers' public events.
 *
 * Same LMDB store as the syncer, but a DIFFERENT config: this one installs a
 * reject-everything write policy. That is what makes the mirror publicly
 * readable without being publicly writable, because a policy that blocks
 * strangers would otherwise block the syncer too — both arrive as plain IP4
 * writes and strfry cannot tell them apart.
 */
export function renderMirrorConf(m: NetizenManifest): string {
  return `${header(m, "Nostr federation mirror (read-only)")}db = "/app/mirror-db/"
relay {
  bind = "0.0.0.0"
  port = 7777
  info {
    name = "${m.name} Federation Mirror"
    description = "Public events mirrored from ${m.id}'s declared peers. Read-only."
  }
  writePolicy { plugin = "/etc/strfry-mirror/reject-all.sh" }
}
`;
}

/**
 * The syncer's config — same store, NO write policy.
 *
 * Only ever loaded by the local federation process, which is why it can write
 * freely. It is never used to serve a socket.
 */
export function renderMirrorSyncConf(m: NetizenManifest): string {
  // NOTE: strfry's config parser rejects the compact `info { a = "x"; b = "y"; }`
  // form that appears in some docs — keys must be on their own lines.
  return `${header(m, "Nostr federation mirror (local syncer)")}db = "/app/mirror-db/"
relay {
  bind = "127.0.0.1"
  port = 7778
  info {
    name = "${m.name} mirror syncer"
    description = "local writer for the federation mirror; never served"
  }
  writePolicy { plugin = "" }
}
`;
}

/** Reject every write arriving over the mirror's socket. The syncer bypasses this by using its own config. */
export function renderMirrorRejectAll(): string {
  return `#!/bin/sh
# The federation mirror is READ-ONLY to the world. Its content arrives only from
# the local syncer, which uses a separate config with no write policy against the
# same store. Anything reaching this socket is by definition not that.
while read -r line; do
  id=$(echo "$line" | sed -n 's/.*"id":"\\([0-9a-f]\\{64\\}\\)".*/\\1/p')
  printf '{"id":"%s","action":"reject","msg":"read-only: this is a federation mirror; publish to the node'"'"'s own relay"}\\n' "$id"
done
`;
}

/** The peer table, rendered for humans — who this node federates with, and why. */
export function renderFederationPeers(m: NetizenManifest): string {
  const peers = m.peers ?? [];
  const rows = peers
    .map((p) => `| ${p.id} | ${p.name} | ${p.relay} | ${p.kinds.join(", ")} | ${p.why} |`)
    .join("\n");
  return `# Federation peers — node "${m.id}"

Generated by \`netizen render\`. Declaring a peer IS the authorisation; change it
in the manifest, not here.

Federation is **pull-only**: this node reads these peers' public events into its
own mirror and never writes into theirs. Their events live in a separate store
from what this node's own members authored, so the members-only write gate on the
authoring relay is untouched.

| id | name | relay | kinds | why |
|---|---|---|---|---|
${rows || "| _none_ | | | | |"}
`;
}

/** How to place the indexer bundle, and what it answers once it is running. */
export function renderIndexerReadme(m: NetizenManifest): string {
  const idx = m.services.indexer!;
  const at = idx.publicRead ?? "http://indexer:8080 (internal)";
  return `# Indexer — node "${m.id}"

Cross-node query layer. Indexes this node's own relay and, when peers are declared,
its federation mirror, then answers questions spanning both.

Place the bundled binary here before \`docker compose up\`:

    pnpm --filter @netizen-labs/indexer build
    scp packages/indexer/dist/indexer.cjs <node>:/opt/netizen/${m.id}/indexer/indexer.cjs

Indexed kinds: ${idx.kinds.join(", ")}. Reachable at ${at}.

    GET /events?q=&kinds=&authors=&since=&until=&node=&limit=
    GET /stats     what this node knows, by source node and kind
    GET /health

\`node\` filters by PROVENANCE — which node an event came from. Without it a
federated answer is an undifferentiated soup, and nobody can tell this town's own
record from a peer's.

Read-only and unauthenticated on purpose: everything here came off world-readable
relays, so publishing leaks nothing new, and it is what lets a peer's agent ask
this node a question.
`;
}

export function renderPostgresInit(m: NetizenManifest): string {
  const dbs = postgresDatabases(m);
  const lines = dbs
    .map((d) => {
      const createDb =
        d === "synapse"
          ? `CREATE DATABASE synapse OWNER synapse ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' TEMPLATE template0`
          : `CREATE DATABASE ${d} OWNER ${d}`;
      return `ensure_role ${d}
ensure_db ${d} "${createDb}"`;
    })
    .join("\n");
  return `#!/bin/bash
# Generated by netizen render — per-service roles + databases for node "${m.id}".
#
# Runs BOTH as a docker-entrypoint-initdb.d script (fresh cluster) AND from
# bootstrap on every apply. The entrypoint hook only fires when the data
# directory is EMPTY, so a service added later would never get its role — which
# is exactly how Matrix failed with 'password authentication failed for user
# "mas"' on a cluster first initialised when only Nextcloud existed.
# Every step is idempotent, so re-running is always safe.
set -e
PSQL="psql -v ON_ERROR_STOP=1 --username \${POSTGRES_USER:-postgres} --no-psqlrc -tAc"

ensure_role() {   # ensure_role <name>
  if [ "$($PSQL "SELECT 1 FROM pg_roles WHERE rolname='$1'")" = "1" ]; then
    $PSQL "ALTER ROLE $1 WITH LOGIN PASSWORD '\${POSTGRES_PASSWORD}'" >/dev/null
  else
    $PSQL "CREATE ROLE $1 LOGIN PASSWORD '\${POSTGRES_PASSWORD}'" >/dev/null
    echo "created role $1"
  fi
}

ensure_db() {     # ensure_db <name> <create-statement>
  if [ "$($PSQL "SELECT 1 FROM pg_database WHERE datname='$1'")" != "1" ]; then
    $PSQL "$2" >/dev/null
    echo "created database $1"
  fi
}

${lines || "true"}
echo "postgres: roles and databases ready"
`;
}

/** Which services need their own role + database on this node. */
export function postgresDatabases(m: NetizenManifest): string[] {
  const ws = m.services.workspace;
  const dbs: string[] = [];
  if (ws?.nextcloud) dbs.push("nextcloud");
  if (m.services.chat?.matrix) dbs.push("synapse", "mas");
  if (ws?.wiki) dbs.push("xwiki");
  if (ws?.project) dbs.push("openproject");
  // The indexer gets its own role and database like every other service, so it is
  // created by the installer rather than by hand on the box.
  if (m.services.indexer) dbs.push("indexer");
  return dbs;
}

export function backupTargets(m: NetizenManifest): Array<"postgres" | "nextcloud" | "strfry"> {
  const declared = m.operations?.backup?.include;
  const available: Array<"postgres" | "nextcloud" | "strfry"> = [];
  if (composeNeedsPostgres(m)) available.push("postgres");
  if (m.services.workspace?.nextcloud) available.push("nextcloud");
  if (m.services.chat?.nostr) available.push("strfry");
  // An explicit include list narrows, but can never name a target the node does
  // not run — that would produce a backup that silently skips.
  return declared ? available.filter((t) => declared.includes(t)) : available;
}

/**
 * Nightly backup. Correctness notes, each learned from a real failure mode:
 *
 * - **Postgres** goes through `pg_dump -Fc`, not a file copy. A snapshot of a
 *   running Postgres is crash-consistent, not transaction-consistent — it can
 *   restore into a corrupt database.
 * - **Nextcloud** files and its database must agree, so both are captured inside
 *   ONE maintenance-mode window. The `trap` is not decoration: without it a
 *   failed backup leaves the town's cloud offline until a human notices.
 * - **strfry** is LMDB. Copying a live LMDB file can capture a torn write, so we
 *   use strfry's own exporter (JSONL), which is consistent by construction.
 * - Every run writes `ops/status.json` — see `renderBackupStatusContract`.
 */
export function renderBackupScript(m: NetizenManifest): string {
  const targets = backupTargets(m);
  const retention = m.operations?.backup?.retentionDays ?? 14;
  const offsite = m.operations?.backup?.offsite ?? "none";

  const pg = targets.includes("postgres")
    ? `
# --- Postgres: every non-template database, custom format (pg_restore-able).
# Enumerated live rather than hardcoded, so a database added later is not silently missed.
for db in $(dc exec -T postgres psql -U postgres -Atc \\
      "select datname from pg_database where not datistemplate and datname <> 'postgres'" \\
      | tr -d '\\r'); do
  step "postgres/$db"
  if dc exec -T postgres pg_dump -U postgres -Fc "$db" > "$DEST/pg-$db.dump"; then
    record "pg-$db.dump"
  else
    fail "pg_dump $db"
  fi
done`
    : "";

  const ncOn = targets.includes("nextcloud")
    ? `
# --- Nextcloud: files + database must agree, so both happen inside ONE
# maintenance window. The trap guarantees the window closes even if we die.
step "nextcloud/maintenance-on"
occ() { dc exec -T -u www-data nextcloud php occ "$@"; }
maintenance_off() { occ maintenance:mode --off >/dev/null 2>&1 || true; }
trap 'maintenance_off' EXIT INT TERM
occ maintenance:mode --on >/dev/null || fail "could not enter maintenance mode"

step "nextcloud/data"
if dc exec -T nextcloud tar -C /var/www/html -cf - data 2>/dev/null | gzip > "$DEST/nextcloud-data.tar.gz"; then
  record "nextcloud-data.tar.gz"
else
  fail "nextcloud data tar"
fi`
    : "";

  const ncOff = targets.includes("nextcloud")
    ? `
step "nextcloud/maintenance-off"
maintenance_off
trap - EXIT INT TERM`
    : "";

  const strfry = targets.includes("strfry")
    ? `
# --- strfry: export events as JSONL. Never copy a live LMDB file — a live LMDB
# can be captured mid-write. The binary is at /app/strfry and is NOT on PATH in
# the official image, so it must be called by absolute path.
step "strfry/export"
if dc exec -T strfry /app/strfry export > "$DEST/strfry-events.jsonl" 2>/dev/null; then
  RELAY_EVENTS=$(wc -l < "$DEST/strfry-events.jsonl" | tr -d ' ')
  gzip -f "$DEST/strfry-events.jsonl"
  # A relay with no events is normal (members-only writes, empty allow-list), so
  # this artifact may legitimately be empty — unlike a database dump, where empty
  # always means failure. Alarming nightly on a healthy state is how real alarms
  # get ignored, so record the count instead of raising an error.
  record_allow_empty "strfry-events.jsonl.gz"
else
  fail "strfry export"
fi

# The relay write allow-list is state too — small, and losing it silently
# un-gates or locks out every citizen.
[ -f strfry-policy/members.txt ] && cp strfry-policy/members.txt "$DEST/" && record "members.txt"`
    : "";

  const offsitePush =
    offsite === "none"
      ? `
# --- Off-box: NOT configured in the manifest (operations.backup.offsite: "none").
# A backup that lives only on the machine it protects is not a backup.
OFFSITE_STATE="disabled-by-manifest"`
      : `
# --- Off-box push. A snapshot on the same provider dies with the account, so the
# only backup that counts is the one on different hardware. Activates the moment
# the two refs below exist in .env — until then it says so, loudly, in status.json.
if [ -n "\${BACKUP_RESTIC_REPOSITORY:-}" ] && [ -n "\${BACKUP_RESTIC_PASSWORD:-}" ]; then
  step "offsite/restic"
  export RESTIC_REPOSITORY="$BACKUP_RESTIC_REPOSITORY"
  export RESTIC_PASSWORD="$BACKUP_RESTIC_PASSWORD"
  command -v restic >/dev/null 2>&1 || apt-get -y install restic >/dev/null 2>&1 || true
  restic snapshots >/dev/null 2>&1 || restic init >/dev/null 2>&1 || true
  if restic backup --tag "${m.id}" "$DEST" >/dev/null 2>&1 \\
     && restic forget --keep-daily ${retention} --keep-weekly 8 --prune >/dev/null 2>&1; then
    OFFSITE_STATE="ok"
  else
    OFFSITE_STATE="failed"; fail "restic push"
  fi
else
  OFFSITE_STATE="unconfigured"
  warn "BACKUP_RESTIC_REPOSITORY / BACKUP_RESTIC_PASSWORD unset — dumps are ON THIS BOX ONLY."
fi`;

  return `#!/usr/bin/env bash
# Generated by \`netizen render\` — nightly backup for node "${m.id}".
# Idempotent, safe to run by hand: bash ops/backup.sh
#
# Restore with ops/restore.sh. An untested backup is a belief, not a backup.
set -uo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && { set -a; . ./.env; set +a

# 2a. Own the deploy directory. rsync preserves the CLIENT's uid/gid, so without
# this the node's config tree ends up owned by whichever laptop ran the deploy,
# and world-traversable.
chown -R root:root . 2>/dev/null || true
chmod 700 . 2>/dev/null || true; }

ROOT="\${BACKUP_ROOT:-/var/backups/netizen}"
STAMP="$(date -u +%Y-%m-%dT%H-%M-%SZ)"
DEST="$ROOT/$STAMP"
STATUS="$(pwd)/ops/status.json"
STARTED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
T0=$SECONDS
ERRORS=0
ARTIFACTS=""
OFFSITE_STATE="unconfigured"
RELAY_EVENTS=0

mkdir -p "$DEST"
chmod 700 "$ROOT" "$DEST"

dc() { docker compose "$@"; }
step() { echo "[backup] $1"; }
warn() { echo "[backup] WARN: $1" >&2; }
fail() { echo "[backup] ERROR: $1" >&2; ERRORS=$((ERRORS + 1)); }
_add_artifact() {
  local b; b=$(stat -c%s "$DEST/$1" 2>/dev/null || echo 0)
  ARTIFACTS="$ARTIFACTS{\\"name\\":\\"$1\\",\\"bytes\\":$b},"
}
record() {
  _add_artifact "$1"
  # A zero-byte dump is a failure wearing a success costume: the run "completed",
  # the file exists, and there is nothing in it to restore from.
  [ "$(stat -c%s "$DEST/$1" 2>/dev/null || echo 0)" -gt 0 ] || fail "$1 is empty"
}
# For artifacts where empty is a legitimate state, not a failure.
record_allow_empty() { _add_artifact "$1"; }
${pg}
${ncOn}
${strfry}
${ncOff}
${offsitePush}

# --- Retention. Local dumps only; offsite retention is restic's own policy.
step "prune/local (keep ${retention}d)"
find "$ROOT" -mindepth 1 -maxdepth 1 -type d -mtime +${retention} -exec rm -rf {} + 2>/dev/null || true

# --- Machine-readable result. Written LAST and atomically, so a reader never
# sees a half-written file and an agent can trust what it parses.
TOTAL=$(du -sb "$DEST" 2>/dev/null | cut -f1 || echo 0)
mkdir -p "$(dirname "$STATUS")"
cat > "$STATUS.tmp" <<JSON
{
  "node": "${m.id}",
  "kind": "backup",
  "startedAt": "$STARTED",
  "finishedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "durationSeconds": $((SECONDS - T0)),
  "ok": $([ "$ERRORS" -eq 0 ] && echo true || echo false),
  "errors": $ERRORS,
  "destination": "$DEST",
  "totalBytes": \${TOTAL:-0},
  "offsite": "$OFFSITE_STATE",
  "retentionDays": ${retention},${targets.includes("strfry") ? '\n  "relayEvents": $RELAY_EVENTS,' : ""}
  "artifacts": [\${ARTIFACTS%,}]
}
JSON
mv "$STATUS.tmp" "$STATUS"

if [ "$ERRORS" -eq 0 ]; then
  echo "[backup] ok — $DEST (offsite: $OFFSITE_STATE)"
else
  echo "[backup] FAILED with $ERRORS error(s) — see $STATUS" >&2
fi
exit "$ERRORS"
`;
}

/**
 * Restore. Deliberately blunt and deliberately manual: it overwrites live data,
 * so it refuses to run without --yes and always names what it is about to touch.
 */
export function renderRestoreScript(m: NetizenManifest): string {
  const targets = backupTargets(m);
  return `#!/usr/bin/env bash
# Generated by \`netizen render\` — restore node "${m.id}" from a backup directory.
#
#   bash ops/restore.sh <backup-dir> --yes            # everything in that dir
#   bash ops/restore.sh <backup-dir> --yes --only pg-nextcloud.dump
#
# DESTRUCTIVE: overwrites the live database and/or files. There is no undo.
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && { set -a; . ./.env; set +a; }

SRC="\${1:-}"
shift || true
ONLY=""
CONFIRM=""
while [ $# -gt 0 ]; do
  case "$1" in
    --yes) CONFIRM=1 ;;
    --only) ONLY="\${2:-}"; shift ;;
  esac
  shift
done

[ -d "$SRC" ] || { echo "usage: restore.sh <backup-dir> --yes [--only FILE]" >&2; exit 2; }
echo "About to restore node \\"${m.id}\\" from: $SRC"
ls -la "$SRC"
[ -n "$CONFIRM" ] || { echo; echo "Refusing to overwrite live data without --yes." >&2; exit 2; }

dc() { docker compose "$@"; }
want() { [ -z "$ONLY" ] || [ "$ONLY" = "$1" ]; }
${
  targets.includes("nextcloud")
    ? `
# Files and database must be restored inside one maintenance window, for the same
# reason they are captured inside one.
if ls "$SRC"/nextcloud-data.tar.gz "$SRC"/pg-nextcloud.dump >/dev/null 2>&1; then
  dc exec -T -u www-data nextcloud php occ maintenance:mode --on >/dev/null || true
  trap 'dc exec -T -u www-data nextcloud php occ maintenance:mode --off >/dev/null 2>&1 || true' EXIT
fi
`
    : ""
}
for dump in "$SRC"/pg-*.dump; do
  [ -e "$dump" ] || continue
  base="$(basename "$dump")"
  want "$base" || continue
  db="\${base#pg-}"; db="\${db%.dump}"
  echo "[restore] postgres/$db"
  # --clean --if-exists makes this repeatable; a half-restored database is worse
  # than a missing one.
  dc exec -T postgres pg_restore -U postgres --clean --if-exists -d "$db" < "$dump" \\
    || echo "[restore] pg_restore reported non-fatal errors for $db (usual for --clean on a fresh db)" >&2
done
${
  targets.includes("nextcloud")
    ? `
if [ -f "$SRC/nextcloud-data.tar.gz" ] && want "nextcloud-data.tar.gz"; then
  echo "[restore] nextcloud/data"
  gunzip -c "$SRC/nextcloud-data.tar.gz" | dc exec -T nextcloud tar -C /var/www/html -xf -
  dc exec -T -u www-data nextcloud php occ maintenance:repair >/dev/null 2>&1 || true
  dc exec -T -u www-data nextcloud php occ files:scan --all >/dev/null 2>&1 || true
fi

dc exec -T -u www-data nextcloud php occ maintenance:mode --off >/dev/null 2>&1 || true
trap - EXIT
`
    : ""
}${
  targets.includes("strfry")
    ? `
if [ -f "$SRC/strfry-events.jsonl.gz" ] && want "strfry-events.jsonl.gz"; then
  echo "[restore] strfry/import"
  gunzip -c "$SRC/strfry-events.jsonl.gz" | dc exec -T strfry strfry import
fi
[ -f "$SRC/members.txt" ] && want "members.txt" && cp "$SRC/members.txt" strfry-policy/members.txt
`
    : ""
}
echo "[restore] done. Verify before trusting it: docker compose ps && curl -sf localhost"
`;
}

/** systemd units — chosen over cron: real status, journald logs, and a recorded last-run. */
export function renderBackupUnits(m: NetizenManifest): { service: string; timer: string } {
  const schedule = m.operations?.backup?.schedule ?? "02:30";
  return {
    service: `[Unit]
Description=Netizen node "${m.id}" — nightly backup
Documentation=file:///opt/netizen/${m.id}/ops/README.md
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
WorkingDirectory=/opt/netizen/${m.id}
ExecStart=/usr/bin/env bash /opt/netizen/${m.id}/ops/backup.sh
# A backup that hangs is a backup that never runs again.
TimeoutStartSec=3600
`,
    timer: `[Unit]
Description=Netizen node "${m.id}" — nightly backup timer

[Timer]
OnCalendar=${schedule}
# Spread load and avoid every node in a fleet hitting its Storage Box at once.
RandomizedDelaySec=900
# If the box was off at 02:30, run at next boot rather than skipping the night.
Persistent=true

[Install]
WantedBy=timers.target
`,
  };
}

/**
 * Host hardening. Only the items that are safe to automate: SSH policy and
 * fail2ban. The firewall is deliberately NOT here — see ops/README.md: Docker
 * writes its own iptables rules and bypasses ufw, so the only firewall that
 * works sits OUTSIDE the box (Hetzner Cloud Firewall) and cannot be rendered.
 */
export function renderHardeningScript(m: NetizenManifest): string {
  const h = m.operations?.hardening ?? {};
  const ssh =
    h.sshPasswordAuth === false
      ? `
# --- SSH: keys only.
#
# Read the EFFECTIVE config (sshd -T), not sshd_config: a later Include can
# override whatever you just wrote, so grepping the file proves nothing.
#
# Captured into a variable rather than piped into grep. With \`set -o pipefail\`,
# \`sshd -T | grep -q\` is a NON-DETERMINISTIC FAIL-OPEN: grep -q exits at the
# first match, sshd takes SIGPIPE and returns 141, pipefail promotes that to the
# pipeline status, the test reads as "no match" and the script reports
# "already off" while changing nothing. That exact bug shipped once and was only
# caught by checking the box afterwards. A security check that cannot measure
# must SAY SO, never assume it is already compliant.
step "ssh/password-auth-off"
sshd_effective="$(sshd -T 2>/dev/null)" || sshd_effective=""
# \`case\` glob, not \`grep\` — no pipe at all, so there is nothing to SIGPIPE.
# All three states are handled EXPLICITLY, including "could not determine",
# which is an error rather than a silent pass.
case "$sshd_effective" in
  *"passwordauthentication yes"*)
    # Refuse to lock ourselves out: only proceed if a key is actually installed.
    if [ -s /root/.ssh/authorized_keys ]; then
      f=/etc/ssh/sshd_config.d/60-netizen-hardening.conf
      mkdir -p /etc/ssh/sshd_config.d
      printf 'PasswordAuthentication no\\nKbdInteractiveAuthentication no\\n' > "$f"
      chmod 644 "$f"
      if sshd -t 2>/dev/null; then
        systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true
        # Verify the change actually took. Applying is not the same as working.
        sshd_after="$(sshd -T 2>/dev/null)" || sshd_after=""
        case "$sshd_after" in
          *"passwordauthentication no"*) echo "[harden] SSH password auth disabled (verified)" ;;
          *)
            echo "[harden] ERROR: wrote $f but sshd does not report password auth off" >&2
            HARDEN_ERRORS=$((HARDEN_ERRORS + 1)) ;;
        esac
      else
        rm -f "$f"
        echo "[harden] ERROR: sshd config test failed — reverted, sshd untouched" >&2
        HARDEN_ERRORS=$((HARDEN_ERRORS + 1))
      fi
    else
      echo "[harden] REFUSED: /root/.ssh/authorized_keys is empty — disabling passwords would lock you out" >&2
      HARDEN_ERRORS=$((HARDEN_ERRORS + 1))
    fi ;;
  *"passwordauthentication no"*)
    echo "[harden] SSH password auth already off (verified)" ;;
  *)
    echo "[harden] ERROR: cannot read effective sshd config — refusing to claim SSH is hardened" >&2
    HARDEN_ERRORS=$((HARDEN_ERRORS + 1)) ;;
esac`
      : "";
  const f2b = h.fail2ban
    ? `
step "fail2ban"
if ! systemctl is-active --quiet fail2ban; then
  DEBIAN_FRONTEND=noninteractive apt-get update -qq >/dev/null 2>&1 || true
  DEBIAN_FRONTEND=noninteractive apt-get -y install fail2ban >/dev/null 2>&1 || true
  systemctl enable --now fail2ban >/dev/null 2>&1 || true
fi
# Assert the end state rather than assuming the install worked.
if systemctl is-active --quiet fail2ban; then
  echo "[harden] fail2ban: active"
else
  echo "[harden] ERROR: fail2ban is not active" >&2
  HARDEN_ERRORS=$((HARDEN_ERRORS + 1))
fi`
    : "";
  return `#!/usr/bin/env bash
# Generated by \`netizen render\` — host hardening for node "${m.id}". Idempotent.
set -uo pipefail
HARDEN_ERRORS=0
step() { echo "[harden] $1"; }
${ssh}
${f2b}

# --- Firewall: intentionally not automated here.
# Docker writes its own iptables rules and BYPASSES ufw — a published container
# port stays reachable even when \`ufw status\` says "deny". Use the Hetzner Cloud
# Firewall (outside the host, unbypassable): allow 22, 80, 443 only.
# (Captured, not piped — same pipefail/SIGPIPE trap as the sshd check above.)
ufw_state="$(ufw status 2>/dev/null)" || ufw_state=""
case "$ufw_state" in
  *"Status: active"*)
    echo "[harden] NOTE: ufw is active but does NOT protect published Docker ports. Use a cloud firewall." >&2 ;;
esac

if [ "$HARDEN_ERRORS" -eq 0 ]; then
  echo "[harden] done — all checks verified"
else
  echo "[harden] done with $HARDEN_ERRORS problem(s) — the node is NOT hardened as declared" >&2
fi
exit "$HARDEN_ERRORS"
`;
}

/**
 * The contract an AI agent reads. Kept next to the data it describes so the
 * schema and the producer cannot drift apart.
 */
export function renderOpsReadme(m: NetizenManifest): string {
  const targets = backupTargets(m);
  const schedule = m.operations?.backup?.schedule ?? "02:30";
  return `# Operations — node "${m.id}"

Generated by \`netizen render\`. **Do not hand-patch these on the box** — change the
manifest and re-run \`netizen up\`, or the next render silently reverts you.

## Backup

Nightly at \`${schedule}\` via \`netizen-backup.timer\`. Targets: ${targets.join(", ") || "none"}.

    systemctl list-timers netizen-backup.timer   # when it next runs
    journalctl -u netizen-backup.service -n 50   # what happened last night
    bash ops/backup.sh                           # run one now

**Restore — test it before you need it:**

    bash ops/restore.sh /var/backups/netizen/<stamp> --yes

An untested backup is a belief, not a backup.

### Off-box

Local dumps protect against *corruption*, not against *losing the box*. Off-box push
activates the moment these two land in \`.env\`:

    BACKUP_RESTIC_REPOSITORY=sftp:uXXXXXX@uXXXXXX.your-storagebox.de:/backups/${m.id}
    BACKUP_RESTIC_PASSWORD=<long random string — LOSE THIS AND THE BACKUPS ARE UNREADABLE>

Until then \`ops/status.json\` reports \`"offsite": "unconfigured"\` and the nightly run
warns. That is deliberate: silence would read as safety.

## Health as data (for AI agents)

\`ops/status.json\` is the machine-readable result of the last backup — agents read
node state as **data**, never by scraping human prose:

    { "node": "${m.id}", "kind": "backup", "ok": true, "errors": 0,
      "finishedAt": "...", "durationSeconds": 12, "totalBytes": 145000000,
      "offsite": "unconfigured", "retentionDays": ${m.operations?.backup?.retentionDays ?? 14},
      "artifacts": [ { "name": "pg-nextcloud.dump", "bytes": 17000000 } ] }

Stable guarantees an agent may rely on: written **atomically** (never half-read),
\`ok\` is false whenever \`errors > 0\`, and a **zero-byte artifact counts as an
error** — a failed dump must never look like a successful one.

\`netizen doctor --json\` emits the same shape for the whole node, so an agent can
diff intent (manifest) against reality (box) without a human in the loop.

## Firewall — the one thing not automated

Docker writes its own iptables rules and **bypasses \`ufw\`**. A published port stays
reachable even when \`ufw\` says "deny". Use the **Hetzner Cloud Firewall** (outside
the host): allow **22, 80, 443** only.
`;
}

/** LiteLLM gateway config — model routing + the node's data-egress posture. */
export function renderLiteLlmConfig(m: NetizenManifest): string {
  const models = Object.entries(m.ai?.models ?? {})
    .map(([role, model]) => `  - model_name: ${role}\n    litellm_params:\n      model: ${model}`)
    .join("\n");
  const tier = m.ai?.sovereignty?.tier ?? "unset";
  const policy = m.ai?.sovereignty?.dataEgressPolicy ?? "unset";
  return `# Generated by \`netizen render\` — AI gateway for node "${m.id}".
# Sovereignty tier: ${tier} · data-egress policy: ${policy}
# API keys come from ./.env (never this file).
model_list:
${models || "  []"}
`;
}

export function renderBundleReadme(m: NetizenManifest): string {
  return `# ${m.name} — Netizen node bundle

Generated by \`netizen render\` from a Netizen Node Manifest. This is the sovereign
node for **${m.name}** (id: \`${m.id}\`).

A **full sovereign stack** — identity, communication, workspace, money rails and AI —
on infrastructure you own. Everything below is generated from one manifest.

## Deploy

1. Provision one box (Ubuntu + Docker) and point DNS at it for every subdomain in
   \`Caddyfile\`.
2. Put a \`.env\` next to this file with every reference listed in \`SECRETS.md\`
   (secrets are referenced, never written into the bundle).
3. \`sudo bash bootstrap.sh\` — or \`netizen up <manifest> --host user@box\` from your
   machine. Brings up the whole declared stack behind Caddy with auto-TLS.
4. Run the post-config steps in \`PLAN.md\` (each service's OIDC provider against the
   keystone — they are idempotent and safe to re-run).
5. Set \`web.env\` on the app host and redeploy so the dashboard tiles light up.

Follow \`PLAN.md\` for the exact ordered, idempotent steps.

## What this node runs

Only what the manifest declares. Every service authenticates against **your own**
identity keystone, so one wallet-based sign-in spans all of them — and the same
identity model makes AI agents members alongside people.
`;
}

/** Idempotent on-box apply script. Run by `netizen up` (or by hand). Re-runnable. */
export function renderBootstrap(m: NetizenManifest): string {
  const hasNextcloud = !!m.services.workspace?.nextcloud;
  const nc = hasNextcloud
    ? `
# 4. Nextcloud OIDC provider + group folders (once the container is initialized).
if docker compose ps --services 2>/dev/null | grep -qx nextcloud; then
  docker compose exec -T -u www-data \\
    -e NEXTCLOUD_CLIENT_SECRET="$NEXTCLOUD_CLIENT_SECRET" \\
    nextcloud sh < nextcloud/setup.sh \\
    || echo "note: re-run once Nextcloud finished its first-run install"
fi`
    : "";
  // Durability + hardening. Installed here rather than hand-run, so node #2
  // inherits them instead of repeating node #1's gap.
  const ops = [
    m.operations?.backup
      ? `
# 5. Backups. Install the systemd timer (idempotent) — chosen over cron because
# it records a real last-run status the operator (and an agent) can read back.
chmod +x ops/backup.sh ops/restore.sh
install -m 644 ops/netizen-backup.service /etc/systemd/system/netizen-backup.service
install -m 644 ops/netizen-backup.timer   /etc/systemd/system/netizen-backup.timer
systemctl daemon-reload
systemctl enable --now netizen-backup.timer
echo "backup timer: $(systemctl is-active netizen-backup.timer) — next: $(systemctl show -p NextElapseUSecRealtime --value netizen-backup.timer)"`
      : "",
    m.operations?.hardening
      ? `
# 6. Host hardening (SSH policy, fail2ban). Idempotent; refuses to lock you out.
# Its exit status is carried to the END of bootstrap rather than aborting here:
# the rest of the node is already up, and a hardening problem must be reported
# loudly (non-zero \`netizen up\`) instead of silently swallowed.
chmod +x ops/harden.sh
HARDEN_RC=0
bash ops/harden.sh || HARDEN_RC=$?`
      : "",
  ]
    .filter(Boolean)
    .join("\n");
  return `#!/usr/bin/env bash
# Generated by \`netizen render\` — idempotent apply for node "${m.id}". Run ON the box (Ubuntu, sudo).
# Safe to re-run: docker compose converges; every step is create-if-absent.
set -euo pipefail
cd "$(dirname "$0")"

# 1. Docker engine + the compose plugin. Checked SEPARATELY: a box can have
# docker without the plugin, and skipping on \`docker\` alone leaves \`docker
# compose\` broken.
if ! command -v docker >/dev/null 2>&1; then
  apt-get update && apt-get -y install docker.io
  systemctl enable --now docker
fi
if ! docker compose version >/dev/null 2>&1; then
  apt-get update && apt-get -y install docker-compose-plugin \\
    || apt-get -y install docker-compose-v2 \\
    || { echo "ERROR: could not install the docker compose plugin" >&2; exit 1; }
fi

# 2. Secrets — a .env next to this script must supply the refs listed in SECRETS.md.
if [ ! -f .env ]; then
  echo "ERROR: create .env from SECRETS.md (POSTGRES_PASSWORD, ROEBEL_ID_JWKS, ...) before applying." >&2
  echo "Tip: for a secret-free first light, run just the Nostr relay: docker compose up -d strfry" >&2
  exit 1
fi
set -a; . ./.env; set +a

# 2b. Matrix: generate secrets/keys on the box, then substitute them into the
# rendered configs. Synapse and MAS need real values in their YAML (neither reads
# env vars), so the bundle ships \${PLACEHOLDER} templates and we fill them here —
# secrets therefore never exist in the bundle or in git.
if [ -f matrix/generate-secrets.sh ]; then
  bash matrix/generate-secrets.sh
  set -a; . ./.env; set +a
  command -v envsubst >/dev/null 2>&1 || apt-get update -qq && apt-get -y install gettext-base >/dev/null 2>&1 || true
  envsubst < mas/config.yaml            > mas/config.rendered.yaml
  envsubst < synapse/homeserver.yaml    > synapse/homeserver.rendered.yaml
  # Synapse and MAS drop to a NON-ROOT user inside their containers, so a 600
  # root-owned file is unreadable to them and they crash-loop with
  # "Permission denied". The secrets stay protected by the deploy directory
  # being root-owned 700 (below): dockerd is root and can bind-mount the file,
  # while non-root users on the host cannot traverse into the directory.
  chmod 644 mas/config.rendered.yaml synapse/homeserver.rendered.yaml
  chmod 644 matrix/keys/*.pem 2>/dev/null || true
fi

# 2b-bis. The relay write-policy plugin must be EXECUTABLE.
# strfry runs it as a program, and a bundle copied by rsync/scp can easily arrive
# without the exec bit. When the plugin cannot start, strfry fails CLOSED and
# rejects every event with "internal error" — the relay looks alive, the
# allow-list looks correct, and nobody can publish. Cost a full debugging cycle
# on node #1; it is one chmod, so it belongs here rather than in a runbook.
if [ -d strfry-policy ]; then
  chmod +x strfry-policy/*.sh 2>/dev/null || true
fi

# 2c. Ensure every declared service has its Postgres role + database. The
# initdb.d hook only fires on an EMPTY data directory, so services added after
# first boot need this explicit pass against the running cluster.
if [ -f postgres/init/01-databases.sh ]; then
  docker compose up -d postgres >/dev/null 2>&1 || true
  for _ in $(seq 1 30); do
    docker compose exec -T postgres pg_isready -U postgres >/dev/null 2>&1 && break
    sleep 1
  done
  docker compose exec -T -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" postgres \\
    bash /docker-entrypoint-initdb.d/01-databases.sh || echo "note: database provisioning reported an issue"
fi

# 2d. Synapse drops to uid 991 inside its container but a fresh named volume is
# root-owned, so it cannot create its signing key. Fix ownership once, from a
# throwaway container, before Synapse starts.
if [ -f synapse/homeserver.rendered.yaml ]; then
  docker run --rm -v "$(basename "$PWD")_synapse_data:/data" alpine:3 \\
    sh -c 'chown -R 991:991 /data' >/dev/null 2>&1 || true
fi

# 3. Bring up the stack (idempotent).
docker compose up -d

# 3b. Restart Caddy. Its config is a bind mount, so "compose up -d" writes the new
# file but does NOT restart the container. "caddy reload" inside the container was
# observed to report success while continuing to serve the OLD routes, so restart
# is the only reliable way to apply routing changes (~1s of downtime).
docker compose restart caddy 2>/dev/null || true

${nc}
${ops}
echo "Applied node \\"${m.id}\\". Verify: docker compose ps"
${m.operations?.hardening ? 'exit "${HARDEN_RC:-0}"' : ""}
`;
}

/** Walk the manifest and collect every secret reference ($ENV / vault:), deduped. */
export function collectSecretRefs(m: NetizenManifest): string[] {
  const out = new Set<string>();
  const walk = (v: unknown) => {
    if (typeof v === "string") {
      if (/^\$[A-Z0-9_]+$/.test(v) || v.startsWith("vault:")) out.add(v);
    } else if (Array.isArray(v)) v.forEach(walk);
    else if (v && typeof v === "object") Object.values(v).forEach(walk);
  };
  walk(m);
  return [...out].sort();
}

/** What each compose-interpolated secret is for, so the checklist is actionable. */
const COMPOSE_SECRET_NOTES: Record<string, string> = {
  POSTGRES_PASSWORD: "invent one; the installer creates every service role with it",
  SUPABASE_SERVICE_KEY:
    "Supabase service-role key. Without it relay-sync crash-loops, the CitizenNFT allow-list stays EMPTY and nobody can publish to the relay",
  NODE_AGENT_SECRET: "seed the node's agent identity is derived from (Mecky's Nostr key)",
  ANTHROPIC_API_KEY: "only if an agent-watcher is declared; the agent answers @mentions with it",
};

export function renderSecretsChecklist(m: NetizenManifest): string {
  const refs = collectSecretRefs(m);
  const items = refs.map((r) => `- [ ] \`${r}\``);
  // The walk above only sees refs written in the MANIFEST. Services also read env
  // vars that are compose-interpolated directly (the indexer's POSTGRES_PASSWORD,
  // relay-sync's SUPABASE_SERVICE_KEY, the agent's ANTHROPIC_API_KEY). Those are
  // just as required, and an operator who works this checklist to the end and
  // stops would bring the node up with those services crash-looping. Read them
  // off the rendered compose file so this list cannot fall behind the stack.
  const named = new Set(refs.map((r) => r.replace(/^\$/, "")));
  const composeOnly = [
    ...new Set(
      [...renderComposeYml(m).matchAll(/\$\{([A-Z0-9_]{4,})\}/g)]
        .map((x) => x[1])
        .filter((n) => !named.has(n)),
    ),
  ].sort();
  for (const name of composeOnly) {
    items.push(`- [ ] \`$${name}\`${COMPOSE_SECRET_NOTES[name] ? ` — ${COMPOSE_SECRET_NOTES[name]}` : ""}`);
  }
  // Not a manifest field and not compose-interpolated under a plain name.
  if (m.services.metering && !composeOnly.includes("METERING_SETTLER_PRIV")) {
    items.push(
      "- [ ] `METERING_SETTLER_PRIV` — facilitator settler EOA private key (pays gas only; fund with a few xDAI). Generate fresh; never reuse another service's key.",
    );
  }
  return `${header(m, "secrets the operator must supply before \`netizen up\`")}
These are **references** — supply the real values via env / vault at apply time.
They are never written into the bundle.

${items.join("\n")}
`;
}

export function plan(m: NetizenManifest): Step[] {
  const ws = m.services.workspace;
  const hosts = ["id", ...(ws?.nextcloud ? ["cloud"] : []), ...(m.services.chat?.matrix ? ["matrix", "auth", "chat"] : []),
    ...(m.services.chat?.nostr ? ["relay"] : []), ...(ws?.mail ? ["mail"] : []), ...(ws?.wiki ? ["wiki"] : []),
    ...(ws?.video ? ["meet"] : []), ...(ws?.project ? ["project"] : []), ...(m.services.buzz ? ["buzz"] : [])];
  const steps: Step[] = [];
  steps.push({ id: "dns", phase: "provision", title: `Point DNS at the box for: ${hosts.join(", ")}` });
  steps.push({ id: "secrets", phase: "provision", title: "Place .env on the box with every ref from SECRETS.md" });
  steps.push({ id: "compose", phase: "services", title: "docker compose up -d — brings up the whole declared stack" });
  // A node with no identity section has no keystone to stand up or verify.
  if (m.identity)
    steps.push(
      m.identity.idp.hosted === "external"
        ? { id: "identity", phase: "identity", title: `Keystone hosted externally at ${m.identity.idp.issuer} — verify discovery resolves; nothing to deploy here` }
        : { id: "roebel-id", phase: "identity", title: "Keystone live (roebel-id.env) — the single sign-in for every service below" },
  );
  // Gate on the SERVICE, like every sibling step below — a relying party may stay
  // registered on an external keystone long after the node stops deploying the
  // service, and a plan step that names a script the bundle does not ship sends
  // the operator looking for a missing file on a fresh box.
  if (ws?.nextcloud && rp(m, "nextcloud")) steps.push({ id: "nextcloud-oidc", phase: "workspace", title: "Run nextcloud/setup.sh (OIDC provider + group folder per org)" });
  if (ws?.mail) steps.push({ id: "mail-oidc", phase: "workspace", title: "Point Open-Xchange at the keystone (OIDC) + its IMAP/SMTP backend" });
  if (ws?.wiki) steps.push({ id: "wiki-oidc", phase: "workspace", title: "Enable the XWiki OIDC provider against the keystone" });
  if (ws?.video) steps.push({ id: "video-auth", phase: "workspace", title: "Jitsi JWT auth from the keystone session (+ prosody/jicofo/jvb, UDP 10000)" });
  if (ws?.project) steps.push({ id: "project-oidc", phase: "workspace", title: "Enable the OpenProject OIDC provider against the keystone" });
  if (m.services.chat?.matrix) steps.push({ id: "mas-oidc", phase: "chat", title: "Apply mas/config.yaml (upstream = the keystone) and restart MAS" });
  if (m.services.chat?.nostr) steps.push({ id: "nostr-relay", phase: "chat", title: "Nostr relay up behind Caddy, members-only writes (strfry-policy/)" });
  if (m.services.buzz)
    steps.push({
      id: "buzz",
      phase: "workspace",
      title: `Agentic workspace (Buzz) up at ${m.services.buzz.url} — closed relay, membership relay-signed (kind:13534)${m.services.buzz.agentPubkeys?.length ? "; run buzz/add-members.sh for the declared agents" : ""}${m.services.buzz.acpAgents?.length ? `; resident 24/7: ${m.services.buzz.acpAgents.map((a) => a.name).join(", ")}` : ""}`,
    });
  if (m.services.indexer && m.services.backend)
    steps.push({
      id: "indexer",
      phase: "chat",
      title: `Indexer up — cross-node queries over ${m.services.indexer.kinds.length} kind(s)${m.services.indexer.publicRead ? ` at ${m.services.indexer.publicRead}` : " (internal)"}`,
    });
  if (m.peers?.length)
    steps.push({
      id: "federation",
      phase: "chat",
      title: `Federation: mirror ${m.peers.length} declared peer(s) over NIP-77 negentropy`,
    });
  if (m.ai?.selfHosted) steps.push({ id: "ai-gateway", phase: "ai", title: "AI gateway (LiteLLM) up — model routing + data-egress policy" });
  steps.push({ id: "web-env", phase: "app", title: "Set web.env on the app host and redeploy (lights up the dashboard tiles)" });
  if (m.operations?.backup) {
    steps.push({ id: "backup", phase: "operations", title: `Enable netizen-backup.timer (${m.operations.backup.schedule ?? "02:30"} nightly)` });
    steps.push({ id: "backup-offsite", phase: "operations", title: "Set BACKUP_RESTIC_REPOSITORY + BACKUP_RESTIC_PASSWORD in .env — until then dumps never leave the box" });
    steps.push({ id: "backup-restore-test", phase: "operations", title: "TEST A RESTORE (ops/restore.sh). An untested backup is a belief, not a backup" });
  }
  if (m.operations?.hardening) steps.push({ id: "harden", phase: "operations", title: "Run ops/harden.sh (SSH keys-only, fail2ban)" });
  steps.push({ id: "firewall", phase: "operations", title: "Hetzner Cloud Firewall: allow 22/80/443 only — ufw cannot protect Docker-published ports" });
  steps.push({ id: "verify", phase: "verify", title: "doctor — discovery reachable, SSO round-trips, tiles light up" });
  return steps;
}

export function renderPlanMd(m: NetizenManifest): string {
  const rows = plan(m)
    .map((s, i) => `${i + 1}. **[${s.phase}]** ${s.title}  \`(${s.id})\``)
    .join("\n");
  return `${header(m, "ordered, idempotent provisioning plan")}\n${rows}\n`;
}

export function renderBundle(m: NetizenManifest): Bundle {
  const files: Record<string, string> = {
    "README.md": renderBundleReadme(m),
    "bootstrap.sh": renderBootstrap(m),
    "docker-compose.yml": renderComposeYml(m),
    // The node's public manifest, served by the indexer at /manifest — the
    // address book that makes the on-chain half (governance, currency)
    // discoverable. Safe to ship: secrets are references by construction.
    "manifest.json": JSON.stringify(m, null, 2),
    "Caddyfile": renderCaddyfile(m),
    // Keystone env only when this node hosts it; an external keystone keeps its
    // own secrets at its host (emitting a stray env file here would mislead).
    ...(!m.identity || m.identity.idp.hosted === "external"
      ? {}
      : { "roebel-id.env": renderRoebelIdEnv(m) }),
    "web.env": renderWebEnv(m),
    "PLAN.md": renderPlanMd(m),
    "SECRETS.md": renderSecretsChecklist(m),
  };
  if (m.services.chat?.matrix) {
    files["mas/config.yaml"] = renderMasConfig(m);
    files["synapse/homeserver.yaml"] = renderSynapseConfig(m);
    files["matrix/generate-secrets.sh"] = renderMatrixSecretsScript();
    files["element/config.json"] = renderElementConfig(m);
  }
  if (m.services.chat?.nostr) {
    files["strfry.conf"] = renderStrfryConf(m);
    // The members-only write policy, shipped with the node (not hand-wired).
    files["strfry-policy/policy.awk"] = renderNostrPolicyAwk(m);
    files["strfry-policy/write-policy.sh"] = renderNostrPolicyWrapper();
    files["strfry-policy/members.txt"] = renderNostrMembers(m);
    files["strfry-policy/add-member.sh"] = renderNostrAddMember();
    if (m.services.metering) {
      files["strfry-policy/metering-excluded.txt"] = renderMeteringExcluded(m);
    }
    // NIP-62/NIP-09 → real LMDB deletion (the executor half; the scanner is a
    // pre-built artifact copied in by the CLI, like relay-sync.cjs).
    files["strfry-vanish/vanish-exec.sh"] = renderVanishExecutor(m);
    // NSP-9: only emitted when peers are declared, so a node that federates with
    // nobody ships no federation machinery at all.
    if (m.services.indexer) files["indexer/README.md"] = renderIndexerReadme(m);
    if (m.peers?.length) {
      files["strfry-mirror/mirror.conf"] = renderMirrorConf(m);
      files["strfry-mirror/mirror-sync.conf"] = renderMirrorSyncConf(m);
      files["strfry-mirror/reject-all.sh"] = renderMirrorRejectAll();
      files["strfry-mirror/sync-peers.sh"] = renderFederationSync(m);
      files["strfry-mirror/PEERS.md"] = renderFederationPeers(m);
    }
  }
  if (m.ai?.selfHosted) {
    files["ai/litellm.yaml"] = renderLiteLlmConfig(m);
  }
  // Only emitted when agents are declared: a buzz block without agentPubkeys is
  // a human-only workspace and ships no membership machinery at all.
  if (m.services.buzz?.agentPubkeys?.length) {
    files["buzz/add-members.sh"] = renderBuzzAddMembers(m);
  }
  if (composeNeedsPostgres(m)) {
    files["postgres/init/01-databases.sh"] = renderPostgresInit(m);
  }
  if (m.services.workspace?.nextcloud) {
    files["nextcloud/setup.sh"] = renderNextcloudSetup(m);
  }
  if (m.operations?.backup) {
    const units = renderBackupUnits(m);
    files["ops/backup.sh"] = renderBackupScript(m);
    files["ops/restore.sh"] = renderRestoreScript(m);
    files["ops/netizen-backup.service"] = units.service;
    files["ops/netizen-backup.timer"] = units.timer;
    files["ops/README.md"] = renderOpsReadme(m);
  }
  if (m.operations?.hardening) {
    files["ops/harden.sh"] = renderHardeningScript(m);
  }
  return { files, plan: plan(m), secretRefs: collectSecretRefs(m) };
}
