import { readFile, rename, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

/**
 * The relay's write-policy allow-list — one lowercase 64-hex Nostr pubkey per
 * line, `#` comments ignored. Read by the strfry plugin on every event, so it
 * must always be complete and valid on disk.
 */

export type ListKind = "members" | "citizens";

const HEADERS: Record<ListKind, string[]> = {
  members: [
    "# Netizen relay MEMBERS list — GENERATED by @netizen-labs/relay-sync.",
    "# Do not edit by hand: the next sync pass overwrites this file.",
    "# One lowercase 64-hex Nostr pubkey per line. Each entry proved joint control",
    "# of a wallet + npub (mutual signatures) and is not revoked; plus declared agent keys.",
    "# Shipped by `netizen render` as strfry-policy/members.txt.",
  ],
  citizens: [
    "# Netizen relay CITIZENS list — GENERATED by @netizen-labs/relay-sync.",
    "# Do not edit by hand: the next sync pass overwrites this file.",
    "# One lowercase 64-hex Nostr pubkey per line. Members whose wallet currently",
    "# holds a CitizenNFT on-chain. Gates citizen-only kinds.",
  ],
};

/** Render the allow-list file contents. Pubkeys are deduped and sorted for a stable diff. */
export function renderAllowList(pubkeys: string[], kind: ListKind = "members"): string {
  const unique = [...new Set(pubkeys.map((p) => p.toLowerCase()))].sort();
  return [...HEADERS[kind], ...unique].join("\n") + "\n";
}

/** The pubkeys currently in a rendered allow-list, ignoring comments and blanks. */
export function parseAllowList(contents: string): string[] {
  return contents
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("#"));
}

/**
 * Write the allow-list atomically: a temp file in the SAME directory, then
 * rename. Two reasons the directory matters — rename is only atomic within a
 * filesystem, and the strfry container bind-mounts the *directory* (a single-file
 * mount would keep pointing at the replaced inode and silently ignore updates).
 *
 * Returns whether the contents actually changed.
 */
export async function writeAllowList(
  path: string,
  pubkeys: string[],
  kind: ListKind = "members",
): Promise<boolean> {
  const next = renderAllowList(pubkeys, kind);

  let current: string | null = null;
  try {
    current = await readFile(path, "utf8");
  } catch {
    current = null; // first run
  }
  if (current === next) return false;

  const temporary = join(dirname(path), `.${basename(path)}.${process.pid}.tmp`);
  await writeFile(temporary, next, "utf8");
  await rename(temporary, path);
  return true;
}
