// PNGs generated by scripts/render-credential-cards.mjs from the assets/cards/*.png masters.
// Metro picks the @2x/@3x variant for the device scale.
import type { ImageSourcePropType } from 'react-native';
import type { CredentialKind } from '@/lib/credentials';

export const CARD_ASPECT = 462 / 290;
export const CARD_RADIUS_AT_462 = 24;

export const CREDENTIAL_ART: Record<CredentialKind, ImageSourcePropType> = {
  guest: require('../../assets/cards/png/guest.png'),
  citizen: require('../../assets/cards/png/citizen.png'),
  attester: require('../../assets/cards/png/attester.png'),
};
